<?php
// $Id$

/**
 * @file
 * TODO: Enter file description here.
 */

/**
 * Implementation of hook_menu().
 */
function jp_blog_menu() { 
  // This is the minimum information you can provide for a menu item.
  
  $items['admin/content/jp_blog'] = array(
    'title' => 'Blogs',
    'description' => 'Manage and add blog configurations.',
    'page callback' => 'jp_blog_admin',
   // 'page arguments' => array('jp_blog_admin'),
    'access arguments' => array('administer jp_blog'),
   // 'file' => 'taxonomy.admin.inc',
  );
  
  $items['admin/content/jp_blog/list'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

 $items['admin/content/jp_blog/add'] = array(
    'title' => 'Add a blog',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('jp_blog_form_config'),
    'access arguments' => array('administer jp_blog'),
    'type' => MENU_LOCAL_TASK,
    'parent' => 'admin/content/jp_blog',
    //'file' => 'taxonomy.admin.inc',
  );

  $items['admin/content/jp_blog/edit/%jp_blog'] = array(
    'title' => 'Edit Blog',
    'page callback' => 'jp_blog_admin_config_edit',
    'page arguments' => array(4),
    'access arguments' => array('administer jp_blog'),
    'type' => MENU_CALLBACK,
  );
  
  $items['admin/content/jp_blog/posts/%jp_blog'] = array(
    'title' => 'Blog Posts',
    'page callback' => 'jp_blog_admin_posts',
    'page arguments' => array(4),
    'access arguments' => array('administer jp_blog'),
    'type' => MENU_CALLBACK,
  );
  
   $items['admin/content/jp_blog/users/%jp_blog'] = array(
    'title' => 'Blog Users',
    'page callback' => 'jp_blog_admin_users',
    'page arguments' => array(4),
    'access arguments' => array('administer jp_blog'),
    'type' => MENU_CALLBACK,
  );
  
   $items['admin/content/jp_blog/users/%/remove/%'] = array(
    'title' => 'Removes a user from a blog',
    'page callback' => 'jp_blog_admin_remove_user',
    'page arguments' => array(4,6),
    'access arguments' => array('administer jp_blog'),
    'type' => MENU_CALLBACK,
  );
  
  $items['admin/content/jp_blog/users/%/add'] = array(
    'title' => 'Add a user to a blog',
    'page callback' => 'jp_blog_admin_add_user',
    'page arguments' => array(4),
    'access arguments' => array('administer jp_blog'),
    'type' => MENU_CALLBACK,
  );
  
   $items['admin/jp_blog/user/autocomplete'] = array(
    'title' => 'autocomplete for user field',
    'page callback' => 'jp_blog_users_autocomplete',
    'access arguments' => array('administer jp_blog'),
    'type' => MENU_CALLBACK,
  );
  //TODO set up front facing urls that will have a different theme
  return $items;
}

/**
 * Implementation of hook_perm().
 */
function jp_blog_perm() {
  return array('administer jp_blog', 'edit jp_blog');
}


/**
 * Implementation of hook_nodeapi().
 */
function jp_blog_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'delete':
      // OPTIONAL: The node is being deleted.
      break;
    case 'delete revision':
      // OPTIONAL: The revision of the node is deleted. You can delete data
      // associated with that revision.
      break;
    case 'insert':
      // OPTIONAL: The node is being created (inserted in the database).
	  //CHECK TO SEE IF THE FOR FIELD FOR BLOG IS SET IF IT IS CALL function to alter url and do stuff
	  if (!empty($node->jp_blog_bid)) {
		$node->path = jp_blog_get_alias_for_node($node->jp_blog_bid, $node->title);
        path_set_alias('node/'. $node->nid, $node->path);
	  }
	  
	  if(!jp_blog_associate_node($node->jp_blog_bid, $node->nid, $node->vid)) {
			//needs error message
	  }
      break;
    case 'load':
      // OPTIONAL: The node is about to be loaded from the database. This hook
      // can be used to load additional data at this time.
		$node->jp_blog = jp_blog_get_blog_by_node($node->nid, $node->vid);
		if ($node->jp_blog) $node->jp_blog_bid = $node->jp_blog->bid;
		else $node->jp_blog_bid = false;
		
      break;
    case 'prepare':
      // OPTIONAL: The node is about to be shown on the add/edit form.
      break;
    case 'presave':
      // OPTIONAL: The node passed validation and is about to be saved. Modules may
      //  use this to make changes to the node before it is saved to the database.
	  //CHECK TO SEE IF THE FOR FIELD FOR BLOG IS SET IF IT IS CALL function to alter url and do stuff
      break;
    case 'update':
      // OPTIONAL: The node is being updated.
	   //CHECK TO SEE IF THE FOR FIELD FOR BLOG IS SET IF IT IS CALL function to alter url and do stuff
	   //var_dump($node);
	   //exit;
	   if (!empty($node->jp_blog_bid)) {
			$node->path = jp_blog_get_alias_for_node($node->jp_blog_bid, $node->title);
		
        	path_set_alias('node/'. $node->nid, $node->path, $node->pid);
	   }
	   
	   if(!jp_blog_associate_node($node->jp_blog_bid, $node->nid, $node->vid)) {
			//needs error message
		}
      break;
    case 'validate':
	//var_dump($node);
	//var_dump($a3);
	  //exit;
      // OPTIONAL: The user has just finished editing the node and is
      // trying to preview or submit it. This hook can be used to check
      // the node data. Errors should be set with form_set_error().
      break;
  }
}

/**
 * Implementation of hook_form_alter().
 */

function jp_blog_form_alter(&$form, &$form_state) {
	global $user;
//$filters = variable_get('formfilter', array());
//$filters['story_node_form']['options'] = 1;
//print_r($filters);
//formfilter_filter_form($form, $filters);
	if ($form['#id'] == 'node-form') {	
		$blogs = jp_blog_get_blogs($user->uid);

		if (!empty($blogs)) {
		$type = $form['old_type']['#value'];
		$fields = array(NULL => t('Not a Blog Post'));
			foreach($blogs as $blog) {
				$fields[$blog->bid] = $blog->name;
			}
			/*$form['jp_blog'] = array(
				'#type' => 'fieldset',
				'#title' => t('Blog Post settings'),
				'#collapsible' => TRUE,
				'#collapsed' => TRUE,
			);*/
			$default_val = (isset($form['#node']->jp_blog_bid)) ? $form['#node']->jp_blog_bid : 0;
			$form['jp_blog']['jp_blog_bid'] = array(
				'#type' => 'select',
				'#title' => t('Blog Assignment'),
				'#options' => $fields,
				'#default_value' => $default_val,
				'#description' => t('Assign to be a blog post.'),
			);
		}
	}
	
	
			//var_dump($form['bid']['#value']);
			$query = db_query("SELECT * from jp_blog where bid = '%d'",$form['bid']['#value']);
			$result = db_fetch_object($query);
			
			//var_dump($result->celeb_twitter_image_path);
			//drupal_set_message('Im in the form');
			 
			 if(!empty($result->header_image_path))
			 {
				  $form['header_image_upload'] = array(
					  '#type' => 'file',
					  '#title' => t('Upload image'),
					  '#size' => 60,
					  '#default_value' => $edit['header_image_upload'],
					  '#description' => t("Celebrity Header Image (840x130)."),
					  '#prefix' => '<div id="celeb_header_image"><span><strong>Current Celebrity Header Image </strong><br /><br /></span><img src="'. url($result->header_image_path) .'" />',
				   );
			   }
			   
			  if(!empty($result->celeb_image_path))
			  {
				   $form['celeb_image_upload'] = array(
					  '#type' => 'file',
					  '#title' => t('Upload celebrity image'),
					  '#size' => 60,
					  '#description' => t("Celebrity Post Icon (80x36)"),
					  '#prefix' => '<div id="celeb_post_icon"><span><strong>Current Celebrity Post Icon </strong><br /><br /></span><img src="'. url($result->celeb_image_path) .'" />',
				   );
			   }
			   
			   if(!empty($result->celeb_name_image_path))
			  {
				   $form['celeb_name_image_upload'] = array(
					  '#type' => 'file',
					  '#title' => t('Upload celebrity image'),
					  '#size' => 60,
					  '#description' => t("Celebrity Name Image"),
					  '#prefix' => '<div id="celeb_name_image"><span><strong>Current Celebrity Name Image </strong><br /><br /></span><img src="'. url($result->celeb_name_image_path) .'" />',
				   );
			   }
			   
			   
			   if(!empty($result->celeb_website_image_path))
			   {
				   $form['celeb_website_image_upload'] = array(
					  '#type' => 'file',
					  '#title' => t('Upload image for celebrity website'),
					  '#size' => 60,
					  '#description' => t("Celebrity Blog Right Bar Thumb (140x105)."),
					  '#prefix' => '<div id="celeb_right_bar_thumb"><span><strong>Current Celebrity Right Bar Thumb</strong><br /><br /></span><img src="'. url($result->celeb_website_image_path) .'" />',
				   );
			   }
			   if(!empty($result->editorial_image_path))
			   {
				   $form['editorial_image_upload'] = array(
					  '#type' => 'file',
					  '#title' => t('Upload editorial image'),
					  '#size' => 60,
					  '#description' => t("Editorial Image for right side bar (80x36)."),
					  '#prefix' => '<div id="editorial_right_bar_thumb"><span><strong>Current Editorial Right Bar Thumb</strong><br /><br /></span><img src="'. url($result->editorial_image_path) .'" />',
				   );
				  
			   }
			   
			   if(!empty($result->celeb_twitter_image_path))
			   {
				   $form['twitter_image_upload'] = array(
					  '#type' => 'file',
					  '#title' => t('Upload image for celebrity twitter'),
					  '#size' => 60,
					  '#description' => t("Celebrity Twitter Image (40X40)."),
					  '#prefix' => '<div id="twitter_right_bar_thumb"><span><strong>Current Celebrity Twitter Image</strong><br /><br /></span><img src="'. url($result->celeb_twitter_image_path) .'" />',
				   );
				}
}

/**
 * Implementation of hook_init().
 */
function jp_blog_init() {

}

function jp_blog_form_config(&$form_state, $edit = array()) {
   $edit += array(
    'name' => '',
    'description' => '',
    'base_uri' => '',
  );
  $form['#attributes'] = array('enctype' => 'multipart/form-data');
  $form['name'] = array(
	'#type' => 'textfield',
    '#title' => t('Title'),
    '#default_value' => $edit['name'],
    '#maxlength' => 255,
    '#description' => t('The name for this blog, e.g., <em>"My Blog"</em>.'),
    '#required' => TRUE,
  );
  
   $options = array('0' => 'Editorial', '1' => 'Celebrity');
   
   $form['blog_type'] = array(
   '#type' => 'select',
   '#description' => t('Please select type of blog'),
   '#title' => t('Blog Type'),
   '#options' => $options,
   '#default_value' => $edit,
   );
   
   $form['top_celeb_blog'] = array(
   '#type' => 'checkbox',
   '#description' => t('Please select if blog is a top celebrity blog'),
   '#title' => t('Top Celeb Blog'),
   '#default_value' => $edit['top_celeb_blog'],
   );
  
  $form['description'] = array(
	'#type' => 'textarea',
    '#title' => t('Description'),
    '#default_value' => $edit['description'],
    '#description' => t('Description of the blog; can be used by modules.'),
  );
 $form['base_uri'] = array(
	'#type' => 'textfield',
    '#title' => t('Base URL'),
    '#default_value' => $edit['base_uri'],
    '#maxlength' => 255,
    '#description' => t('Can onlycontain alpha numeric characters.'),
    '#required' => TRUE,
  );
  $form['editorial_image_upload'] = array(
      '#type' => 'file',
      '#title' => t('Upload editorial image'),
      '#size' => 60,
      '#description' => t("Editorial Image for right side bar (80x36)."),
   );
   $form['editorial_info'] = array(
	'#type' => 'textarea',
    '#title' => t('Editorial Info'),
    '#description' => t('Editorial Info for right side bar.'),
	'#default_value' => $edit['editorial_info'],
  );
  
	//TODO standard form for editing a blog configuration
  $form['header_image_upload'] = array(
      '#type' => 'file',
      '#title' => t('Upload image'),
      '#size' => 60,
      '#description' => t("Celebrity Header Image (840x130)."),
   );
   
   
   $form['celeb_name'] = array(
	'#type' => 'textfield',
    '#title' => t('Celebrity Name'),
    '#default_value' => $edit['celeb_name'],
    '#description' => t('Name of celebrity.'),
  );
  $form['celeb_image_upload'] = array(
      '#type' => 'file',
      '#title' => t('Upload celebrity image'),
      '#size' => 60,
      '#description' => t("Celebrity Post Icon (80x36)."),
   );
   $form['celeb_name_image_upload'] = array(
      '#type' => 'file',
      '#title' => t('Upload image for celebrity name'),
      '#size' => 60,
      '#description' => t("Celebrity Name Image."),
   );
   $form['twitter_name'] = array(
	'#type' => 'textfield',
    '#title' => t('Twitter Account Name'),
    '#default_value' => $edit['twitter_name'],
    '#description' => t('Twitter Account Name.'),
  );
  
   $form['twitter_image_upload'] = array(
      '#type' => 'file',
      '#title' => t('Upload image for celebrity twitter'),
      '#size' => 60,
      '#description' => t("Celebrity Twitter Image."),
   );
   
  $form['celeb_link'] = array(
	'#type' => 'textarea',
    '#title' => t('Celebrity Web Page'),
    '#default_value' => $edit['celeb_link'],
    '#description' => t('Link to celebrity web page. Must include http:// before the url.'),
  );
  $form['website_text'] = array(
	'#type' => 'textarea',
    '#title' => t('Celebrity Website Info'),
    '#description' => t('Info about celebrity website.'),
	'#default_value' => $edit['website_text'],
  );
  
  $form['celeb_website_image_upload'] = array(
      '#type' => 'file',
      '#title' => t('Upload image for celebrity website'),
      '#size' => 60,
      '#description' => t("Celebrity Blog Right Bar Thumb (140x105)."),
   );
   
   
   //TODO add select field for choosing users for this blog
  $form['submit'] = array('#type' => 'submit', '#value' => t('Save'));
  if (isset($edit['bid'])) {
    $form['delete'] = array('#type' => 'submit', '#value' => t('Delete'));
    $form['bid'] = array('#type' => 'value', '#value' => $edit['bid']);
    $form['module'] = array('#type' => 'value', '#value' => $edit['module']);
  }
  return $form;
}

function jp_blog_admin() {
  $jp_blogs = jp_blog_get_blogs();
  $rows = array();
  foreach ($jp_blogs as $jp_blog) {
      $row = array();
      $row[] = $jp_blog->name;
	  $row[] = l(t('Edit Blog'), "admin/content/jp_blog/edit/$jp_blog->bid") . " | " . l(t('Show Posts'), "admin/content/jp_blog/posts/$jp_blog->bid") . " | " . l(t('Show Users'), "admin/content/jp_blog/users/$jp_blog->bid");
      //$row[] = "<a href='admin/content/jp_blog/edit/" . $jp_blog->bid . "'>Edit</a>";
      //TODO will list nodes $row[] = drupal_render($vocabulary['list']);
      $rows[] = array('data' => $row, 'class' => 'draggable');
  }
  if (empty($rows)) {
    $rows[] = array(array('data' => t('No blogs available.'), 'colspan' => '2'));
  }

  $header = array(t('Title'));
  $header[] = array('data' => t('Operations'));
  return theme('table', $header, $rows, array('id' => 'jp_blog'));
  //return $form;
}

function jp_blog_admin_posts($jp_blog) {
  $nodes = jp_blog_get_nodes($jp_blog->bid);
  $rows = array();
  foreach ($nodes as $node) {
      $row = array();
      $row[] = $node->title;
	  $row[] = l(t('Edit'), "node/$node->nid/edit", array( "query" => "?destination=admin/content/jp_blog/posts/" . $jp_blog->bid));
      //$row[] = "<a href='admin/content/jp_blog/edit/" . $jp_blog->bid . "'>Edit</a>";
      //TODO will list nodes $row[] = drupal_render($vocabulary['list']);
      $rows[] = array('data' => $row);
  }
  if (empty($rows)) {
    $rows[] = array(array('data' => t('No posts available.'), 'colspan' => '2'));
  }

  $header = array(t('Title'));
  $header[] = array('data' => t('Operations'));
  $backLink = "<div><a href='" . url('admin/content/jp_blog') . "'>&lt;&lt;Back to Blogs</a></div><br>";
  return $backLink . theme('table', $header, $rows, array('id' => 'jp_blog'));
  //return $form;
}

function jp_blog_username_form(&$form_state, $bid) {

   $form['#action'] = url("admin/content/jp_blog/users/$bid/add");
   $form['#redirect'] = url("admin/content/jp_blog/users/$bid");
   $form['name'] = array(
	'#type' => 'textfield',
    '#title' => t('Add a User'),
	'#autocomplete_path' => 'admin/jp_blog/user/autocomplete',
    '#description' => t('Type in a user you would like to add to this blog'),
   );
   $form['submit'] = array('#type' => 'submit', '#value' => t('Add User'));
   
   return $form;
}

function jp_blog_admin_users($jp_blog) {

  $jpb_users = jp_blog_get_users($jp_blog->bid);
  $rows = array();
 // var_dump($jpb_users);
  foreach ($jpb_users as $jpb_user) {
      $row = array();
      $row[] = $jpb_user->name;
	  $row[] = l(t('Remove'), "admin/content/jp_blog/users/$jp_blog->bid/remove/$jpb_user->uid");
      //$row[] = "<a href='admin/content/jp_blog/edit/" . $jp_blog->bid . "'>Edit</a>";
      //TODO will list nodes $row[] = drupal_render($vocabulary['list']);
      $rows[] = array('data' => $row);
  }
  if (empty($rows)) {
    $rows[] = array(array('data' => t('No users assigned.'), 'colspan' => '2'));
  }

  $header = array(t('Name'));
  $header[] = array('data' => t('Operations'));
  
  $backLink = "<div><a href='" . url('admin/content/jp_blog') . "'>&lt;&lt;Back to Blogs</a></div><br>";
  return $backLink . drupal_get_form('jp_blog_username_form', $jp_blog->bid) . theme('table', $header, $rows, array('id' => 'jp_blog_users'));
  //return $form;
}

function jp_blog_admin_config_edit($jp_blog) {
  if ((isset($_POST['op']) && $_POST['op'] == t('Delete')) || isset($_POST['confirm'])) {
    return drupal_get_form('jp_blog_confirm_delete', $jp_blog->bid);
  }
  return drupal_get_form('jp_blog_form_config', (array)$jp_blog);
}

function jp_blog_form_config_submit($form, &$form_state) {
 // Fix up the nodes array to remove unchecked nodes.
  //$form_state['values']['nodes'] = array_filter($form_state['values']['nodes']);
  switch (jp_blog_save_config($form_state['values'])) {
    case SAVED_NEW:
      drupal_set_message(t('Created new blog %name.', array('%name' => $form_state['values']['name'])));
      watchdog('jp_blog', 'Created new blog %name.', array('%name' => $form_state['values']['name']), WATCHDOG_NOTICE, l(t('edit'), 'admin/content/jp_blog/edit/'. $form_state['values']['bid']));
      break;
    case SAVED_UPDATED:
      drupal_set_message(t('Updated blog %name.', array('%name' => $form_state['values']['name'])));
      watchdog('jp_blog', 'Updated blog %name.', array('%name' => $form_state['values']['name']), WATCHDOG_NOTICE, l(t('edit'), 'admin/content/jp_blog/edit/'. $form_state['values']['bid']));
      break;
  }

  $form_state['bid'] = $form_state['values']['bid'];
  $form_state['redirect'] = 'admin/content/jp_blog';
  return;
  
}

function jp_blog_save_config(&$edit) {
  $edit['nodes'] = empty($edit['nodes']) ? array() : $edit['nodes'];

  if (!isset($edit['module'])) {
    $edit['module'] = 'jp_blog';
  }
  
  //UPLOAD FILE
  $validators = array();
//print_r($edit);
//exit;
//  if (!empty($edit['header_image_upload'])) {
  	$directory = file_directory_path() . "/blog_headers";
  	if (!file_check_directory($directory, FILE_CREATE_DIRECTORY)) {
     	drupal_set_message(t('Error creating the blog header image directory: "%dir" does not exist, or is not writable.', array('%dir' => $directory)), 'error');
  	} else {
	  // FILE_EXISTS_REPLACE allows multiple terms to use the same image without having multiple files.      
	  	$file = file_save_upload('header_image_upload', $validators, $directory, FILE_EXISTS_REPLACE);
	  	if (is_object($file)) {
			// If no errors while uploading, save term-image relation into DB
			$filepath = $directory .'/'. $file->filename;
			$edit['header_image_path'] =  $filepath;
			// TODO see if we need this, i dont think we do cache_clear_all("taxonomy_image:$tid", 'cache_tax_image');
			// make sure Cron doesn't delete this file.
			file_set_status($file, FILE_STATUS_PERMANENT);
			drupal_set_message(t('Image uploaded as @name.', array('@name' => $filepath)));
	  	}
  	}
//  } 

 //if (!empty($edit['celeb_image_upload'])) {
  	$directory = file_directory_path() . "/blog_celebrity";
  	if (!file_check_directory($directory, FILE_CREATE_DIRECTORY)) {
     	drupal_set_message(t('Error creating the blog celebrity image directory: "%dir" does not exist, or is not writable.', array('%dir' => $directory)), 'error');
  	} else {
	  // FILE_EXISTS_REPLACE allows multiple terms to use the same image without having multiple files.      
	  	$file = file_save_upload('celeb_website_image_upload', $validators, $directory, FILE_EXISTS_REPLACE);
	  	if (is_object($file)) {
			// If no errors while uploading, save term-image relation into DB
			$filepath = $directory .'/'. $file->filename;
			$edit['celeb_website_image_path'] =  $filepath;
			// TODO see if we need this, i dont think we do cache_clear_all("taxonomy_image:$tid", 'cache_tax_image');
			// make sure Cron doesn't delete this file.
			file_set_status($file, FILE_STATUS_PERMANENT);
			drupal_set_message(t('Image uploaded as @name.', array('@name' => $filepath)));
	  	}
  	}
  //} 
	
	$directory = file_directory_path() . "/celebrity_website";
  	if (!file_check_directory($directory, FILE_CREATE_DIRECTORY)) {
     	drupal_set_message(t('Error creating the blog celebrity image directory: "%dir" does not exist, or is not writable.', array('%dir' => $directory)), 'error');
  	} else {
	  // FILE_EXISTS_REPLACE allows multiple terms to use the same image without having multiple files.      
	  	$file = file_save_upload('celeb_image_upload', $validators, $directory, FILE_EXISTS_REPLACE);
	  	if (is_object($file)) {
			// If no errors while uploading, save term-image relation into DB
			$filepath = $directory .'/'. $file->filename;
			$edit['celeb_image_path'] =  $filepath;
			// TODO see if we need this, i dont think we do cache_clear_all("taxonomy_image:$tid", 'cache_tax_image');
			// make sure Cron doesn't delete this file.
			file_set_status($file, FILE_STATUS_PERMANENT);
			drupal_set_message(t('Image uploaded as @name.', array('@name' => $filepath)));
	  	}
  	}
	
	$directory = file_directory_path() . "/celebrity_website";
  	if (!file_check_directory($directory, FILE_CREATE_DIRECTORY)) {
     	drupal_set_message(t('Error creating the blog celebrity image directory: "%dir" does not exist, or is not writable.', array('%dir' => $directory)), 'error');
  	} else {
	  // FILE_EXISTS_REPLACE allows multiple terms to use the same image without having multiple files.      
	  	$file = file_save_upload('twitter_image_upload', $validators, $directory, FILE_EXISTS_REPLACE);
	  	if (is_object($file)) {
			// If no errors while uploading, save term-image relation into DB
			$filepath = $directory .'/'. $file->filename;
			$edit['celeb_twitter_image_path'] =  $filepath;
			// TODO see if we need this, i dont think we do cache_clear_all("taxonomy_image:$tid", 'cache_tax_image');
			// make sure Cron doesn't delete this file.
			file_set_status($file, FILE_STATUS_PERMANENT);
			drupal_set_message(t('Image uploaded as @name.', array('@name' => $filepath)));
	  	}
  	}
	
	$directory = file_directory_path() . "/celebrity_website";
  	if (!file_check_directory($directory, FILE_CREATE_DIRECTORY)) {
     	drupal_set_message(t('Error creating the blog celebrity image directory: "%dir" does not exist, or is not writable.', array('%dir' => $directory)), 'error');
  	} else {
	  // FILE_EXISTS_REPLACE allows multiple terms to use the same image without having multiple files.      
	  	$file = file_save_upload('celeb_name_image_upload', $validators, $directory, FILE_EXISTS_REPLACE);
	  	if (is_object($file)) {
			// If no errors while uploading, save term-image relation into DB
			$filepath = $directory .'/'. $file->filename;
			$edit['celeb_name_image_path'] =  $filepath;
			// TODO see if we need this, i dont think we do cache_clear_all("taxonomy_image:$tid", 'cache_tax_image');
			// make sure Cron doesn't delete this file.
			file_set_status($file, FILE_STATUS_PERMANENT);
			drupal_set_message(t('Image uploaded as @name.', array('@name' => $filepath)));
	  	}
  	}
	
	
	$directory = file_directory_path() . "/editorial_images";
  	if (!file_check_directory($directory, FILE_CREATE_DIRECTORY)) {
     	drupal_set_message(t('Error creating the blog editorial images directory: "%dir" does not exist, or is not writable.', array('%dir' => $directory)), 'error');
  	} else {
	  // FILE_EXISTS_REPLACE allows multiple terms to use the same image without having multiple files.      
	  	$file = file_save_upload('editorial_image_upload', $validators, $directory, FILE_EXISTS_REPLACE);
	  	if (is_object($file)) {
			// If no errors while uploading, save term-image relation into DB
			$filepath = $directory .'/'. $file->filename;
			$edit['editorial_image_path'] =  $filepath;
			// TODO see if we need this, i dont think we do cache_clear_all("taxonomy_image:$tid", 'cache_tax_image');
			// make sure Cron doesn't delete this file.
			file_set_status($file, FILE_STATUS_PERMANENT);
			drupal_set_message(t('Image uploaded as @name.', array('@name' => $filepath)));
	  	}
  	}
  
  
  if (!empty($edit['bid']) && !empty($edit['name'])) {
    drupal_write_record('jp_blog', $edit, 'bid');
  /* db_query("DELETE FROM {vocabulary_node_types} WHERE vid = %d", $edit['vid']);
    foreach ($edit['nodes'] as $type => $selected) {
      db_query("INSERT INTO {vocabulary_node_types} (vid, type) VALUES (%d, '%s')", $edit['vid'], $type);
    }
	*/
    // WHAT IS THIS FUNCTION?? module_invoke_all('taxonomy', 'update', 'vocabulary', $edit);
    $status = SAVED_UPDATED;
  } else if (!empty($edit['bid'])) {
   // $status = taxonomy_del_vocabulary($edit['bid']);
  } else {
   drupal_write_record('jp_blog', $edit);
  /*  foreach ($edit['nodes'] as $type => $selected) {
      db_query("INSERT INTO {vocabulary_node_types} (vid, type) VALUES (%d, '%s')", $edit['vid'], $type);
    }
	*/
  //  module_invoke_all('taxonomy', 'insert', 'vocabulary', $edit);
    $status = SAVED_NEW;
  }
  
  //need to set to check whether or not the url exist.
  	$results = db_query("SELECT COUNT(*) FROM {url_alias} WHERE dst = '%s'", $edit['base_uri']);
	
	if($results == 0) {
    	db_query("INSERT INTO {url_alias} (src,dst) VALUES ('%s','%s')", 'blogs/'.$edit['bid'], $edit['base_uri']);
	}else {	
		db_query("DELETE FROM {url_alias} WHERE dst = '%s'", $edit['base_uri']);
		db_query("INSERT INTO {url_alias} (src,dst) VALUES ('%s','%s')", 'blogs/'.$edit['bid'], $edit['base_uri']);
	}
 
  cache_clear_all();

}

function jp_blog_get_blogs($uid=null) {

  if (!$uid) $result = db_query('SELECT * FROM {jp_blog} jp_blog ORDER BY jp_blog.name');
  else $result = db_query('SELECT * FROM {jp_blog} jp_blog INNER JOIN {jp_blog_user} jp_user on jp_user.bid = jp_blog.bid WHERE jp_user.uid = %d ORDER BY jp_blog.name', $uid);
   //$result = db_query('SELECT * FROM {jp_blog} jp_blog ORDER BY jp_blog.name');
  $jp_blogs = array();
  while ($blog = db_fetch_object($result)) {
    // If no node types are associated with a vocabulary, the LEFT JOIN will
    // return a NULL value for type.
    $jp_blogs[$blog->bid] = $blog;
  }

  return $jp_blogs;
}

function jp_blog_load($bid) {
  static $blogs = array();

  if (!isset($blogs[$bid])) {
    // Initialize so if this vocabulary does not exist, we have
    // that cached, and we will not try to load this later.
    $blogs[$bid] = FALSE;
    // Try to load the data and fill up the object.
    $result = db_query('SELECT * FROM {jp_blog} jp_blog WHERE jp_blog.bid = %d', $bid);
    while ($blog = db_fetch_object($result)) {
     $blogs[$bid] = $blog;
    }
  }

  // Return FALSE if this vocabulary does not exist.
  return !empty($blogs[$bid]) ? $blogs[$bid] : FALSE;
}

function jp_blog_associate_node($bid, $nid, $vid) {
	if (empty($bid)) {
		db_query('DELETE FROM {jp_blog_node} WHERE vid= %d', $vid);
	} else {
		$assocNode = array('bid' => $bid, 'nid' => $nid, 'vid' => $vid);
		$results = db_fetch_array(db_query('SELECT vid FROM {jp_blog_node} jp_blog_node WHERE vid= %d', $vid));
		if ( !empty($results)) {
			return drupal_write_record('jp_blog_node', $assocNode, 'vid');
		} else {
			return drupal_write_record('jp_blog_node', $assocNode);
		}
	}
}

function jp_blog_get_blog_by_node($nid, $vid) {
	$result = db_fetch_object(db_query('SELECT jp_blog.* FROM {jp_blog_node} jp_blog_node INNER JOIN jp_blog on jp_blog_node.bid = jp_blog.bid WHERE nid = %d and vid= %d LIMIT 1', $nid, $vid));
	if (!empty($result)) return $result;
	else return FALSE;
}

function jp_blog_get_nodes($bid) {
	$result = db_query('SELECT n.title, n.nid FROM {node} n INNER JOIN {jp_blog_node} jpbn on jpbn.nid = n.nid WHERE jpbn.bid = %d ORDER BY n.nid', $bid);
    $nodes = array();
  while ($node = db_fetch_object($result)) {
    // If no node types are associated with a vocabulary, the LEFT JOIN will
    // return a NULL value for type.
    $nodes[$node->nid] = $node;
  }

  return $nodes;
}

function jp_blog_get_users($bid) {
	$result = db_query('SELECT u.name, u.uid, u.mail FROM {users} u INNER JOIN {jp_blog_user} jpbu on jpbu.uid = u.uid WHERE jpbu.bid = %d ORDER BY u.name', $bid);
    $users = array();
  while ($user = db_fetch_object($result)) {
    // If no node types are associated with a vocabulary, the LEFT JOIN will
    // return a NULL value for type.
    $users[$user->uid] = $user;
  }

  return $users;
}

function jp_blog_admin_add_user($bid) {
    $userObj = user_load(array("name" => $_POST['name']));
	//TODO get uid by username
	$userRec = array('bid' => $bid, 'uid' => $userObj->uid);
	if (drupal_write_record('jp_blog_user', $userRec)) {
		drupal_set_message('User has been added');
	}
	drupal_goto("admin/content/jp_blog/users/$bid");
}

function jp_blog_admin_remove_user($bid, $uid) {
    $userObj = user_load(array("name" => $_POST['name']));
	//TODO get uid by username
	db_query('DELETE FROM {jp_blog_user} WHERE bid= %d and uid = %d', $bid, $uid);
	drupal_set_message('User has been removed');
	drupal_goto("admin/content/jp_blog/users/$bid");
}

function jp_blog_get_alias_for_node($bid, $node_title) {
	$jp_blog = jp_blog_load($bid);
	$node_title = strtolower(str_replace(" ", "-", $node_title));

	return $jp_blog->base_uri . '/' . preg_replace("/[^a-zA-Z0-9_\-\s]/", "", $node_title);
}

function jp_blog_users_autocomplete($string){
  $items = array();  
 // $result = db_query("SELECT uid,  FROM {node} WHERE status = 1 AND title LIKE ''%s%%', $string");
  $result = db_query("SELECT name, uid FROM users WHERE status = 1 AND name LIKE '%s%%'", $string);
    
  while($obj = db_fetch_object($result)) {
    $items[$obj->name] = check_plain($obj->name);
  }
  print drupal_to_js($items); 
  exit();
}

function jp_blog_update_1() {
	$ret = array();
	db_add_field($ret, 'jp_blog', 'celeb_twitter_image_path', array('type' => 'varchar', 'length' => 255, 'not_null' => FALSE, 'default' => '', 'description' => 'Celebrity twitter image.'));
	return $ret;
}

function jp_blog_views_pre_execute(&$view) {
 //drupal_set_message(var_export(array_keys((array)$view->build_info), TRUE));
 // drupal_set_message(var_export($view->build_info, TRUE));
  //drupal_set_message($view->build_info['query_args']);
 global $user; 
 global $blog_id;
 
 global $twitter_name;
 global $celeb_name;
 global $celeb_link;
 global $blog_type;
 global $blog_name;
 global $terms;
 global $twitter_image;
 $args[0] = arg(0);
 $args[1] = arg(1);
 
 
 
 if($args[0] == 'node')
 {
 	$query = db_query("SELECT dst FROM url_alias WHERE src = '%s'",$args[0].'/'.$args[1]);
 	$result = db_fetch_object($query);
 	$url_alias = substr($result->dst,0,stripos($result->dst,"/"));
 
 
  	$query = db_query("SELECT bid FROM jp_blog WHERE base_uri = '%s'",$url_alias);
 	$result = db_fetch_object($query);
 	$blog_id = $result->bid;
 }
 else
 { 
 	$blog_id = $args[1];
 }
 
 
 $query = db_query("SELECT * FROM jp_blog WHERE bid = %d",arg(1));
 $result = db_fetch_object($query);

 $twitter_name = $result->twitter_name; 
 $celeb_name = $result->celeb_name;
 $celeb_link = $result->celeb_link;
 $blog_type = $result->blog_type;
 $blog_name = $result->name;
 
 
   if($view->tag == 'jpblog') {
		
		$sql =  "SELECT 
					/*jpblog*/ DISTINCT(node.nid) AS nid,
					node_comment_statistics.comment_count AS node_comment_statistics_comment_count,
					node.title AS node_title, 
					node.type AS node_type,  
					node.status AS node_status, 
					node.uid AS node_uid, 
					node_revisions.format AS node_revisions_format, 
					node_revisions.teaser AS node_revisions_teaser,
					node.changed AS node_changed,
					node.created AS node_created,
					node_revisions.body AS node_revisions_body,
					node_data_field_img_src.field_img_src_fid AS node_data_field_img_src_field_img_src_fid,
   node_data_field_img_src.field_img_src_list AS node_data_field_img_src_field_img_src_list,
   node_data_field_img_src.field_img_src_data AS node_data_field_img_src_field_img_src_data,
					node_data_field_story_thumb.field_story_thumb_fid AS 																	node_data_field_story_thumb_field_story_thumb_fid,
   					node_data_field_story_thumb.field_story_thumb_list AS node_data_field_story_thumb_field_story_thumb_list,
					node_data_field_story_thumb.field_story_thumb_data AS node_data_field_story_thumb_field_story_thumb_data,
   node_data_field_story_thumb.nid AS node_data_field_story_thumb_nid,
   node_data_field_story_thumb.field_excerpt_value AS node_data_field_story_thumb_field_excerpt_value,
   					jp_blog.base_uri AS jp_blog_base,
					jp_blog.bid AS jp_blog_bid,
					jp_blog.twitter_name AS jp_blog_twitter_name,
					jp_blog.celeb_link AS jp_blog_celeb_link,
					jp_blog.blog_type AS jp_blog_type,
					jp_blog.celeb_image_path AS jp_blog_celeb_website_image
				 FROM 
				 	{node} node
				 INNER JOIN node_comment_statistics node_comment_statistics ON node.nid = node_comment_statistics.nid
				 LEFT JOIN 
				 	{node_revisions} node_revisions ON node.vid = node_revisions.vid 
				 LEFT JOIN 
				 	{jp_blog_node} jp_blog_node on jp_blog_node.nid = node.nid 
				 LEFT JOIN
				 	jp_blog on jp_blog.bid = jp_blog_node.bid
				LEFT JOIN 
				 	content_type_story node_data_field_story_thumb ON node.vid = node_data_field_story_thumb.vid
				LEFT JOIN content_field_img_src node_data_field_img_src ON node.vid = node_data_field_img_src.vid
				
				 WHERE 
				 	(jp_blog_node.bid = ".$blog_id.")
					AND
					(node.type IN ('photo_gallery', 'audio', 'book', 'event', 'link', 'story', 'video'))
					AND
					(node.status <> 0)
					
				ORDER BY 
				 	node.created DESC";
		$view->build_info['query'] =  $sql;
		$view->build_info['count_query'] = $sql;
		//drupal_set_message($view->build_info['query']); 
   } else if($view->tag == 'latest_on_vibes') {
   		
   		$sql =  "SELECT /*latest_on_vibe*/ DISTINCT(node.nid) AS nid,
				   node_comment_statistics.comment_count AS node_comment_statistics_comment_count,
				   node.type AS node_type,
				   node.created AS node_created,
				   node_revisions.teaser AS node_revisions_teaser,
				   node_revisions.format AS node_revisions_format,
				   node.title AS node_title,
				   node_data_field_story_thumb.field_story_thumb_data AS node_data_field_story_thumb_field_story_thumb_data,
				   node_data_field_story_thumb.nid AS node_data_field_story_thumb_nid,
   				  node_data_field_story_thumb.field_excerpt_value AS node_data_field_story_thumb_field_excerpt_value,
				   node.vid AS node_vid,
				   node_data_field_story_thumb.field_story_thumb_fid AS node_data_field_story_thumb_field_story_thumb_fid,
				   node_data_field_story_thumb.field_story_thumb_list AS node_data_field_story_thumb_field_story_thumb_list,
				   node_revisions.body AS node_revisions_body,
				   node_data_field_img_src.field_img_src_fid AS node_data_field_img_src_field_img_src_fid,
				   node_data_field_img_src.field_img_src_list AS node_data_field_img_src_field_img_src_list,
				   node_data_field_img_src.field_img_src_data AS node_data_field_img_src_field_img_src_data,
				   jp_blog.base_uri AS jp_blog_base,
				   jp_blog.blog_type AS jp_blog_type,
				   jp_blog.celeb_image_path AS jp_blog_celeb_website_image,
				   jp_blog.name AS jp_blog_name

				 FROM 
				 	node node 				 
				 INNER JOIN
				 	term_node term_node ON node.vid = term_node.vid				 
				 INNER JOIN 
				 	node_comment_statistics node_comment_statistics ON node.nid = node_comment_statistics.nid
				 LEFT JOIN 
				 	jp_blog_node on jp_blog_node.nid = node.nid 
				 LEFT JOIN
				 	jp_blog on jp_blog.bid = jp_blog_node.bid
				 LEFT JOIN 
				 	node_revisions node_revisions ON node.vid = node_revisions.vid
				 LEFT JOIN 
				 	content_type_story node_data_field_story_thumb ON node.vid = node_data_field_story_thumb.vid
				 LEFT JOIN 
				 	content_field_img_src node_data_field_img_src ON node.vid = node_data_field_img_src.vid
				 WHERE 
				 	(node.type in ('advpoll_ranking', 'advpoll_binary', 'photo_gallery', 'audio', 'book', 'event', 'link', 'story', 'video')) 
				 AND 
				 	(term_node.tid IN (2523, 10, 9, 8, 11, 2612)) 
				 AND 
				 	(node.status <> 0)
				   
				 ORDER BY
				 	node_created DESC
";
					
   		$view->build_info['query'] =  $sql;
		//var_dump($view->build_info['query']);
   		$view->build_info['count_query'] = $sql;
   		$view->build_info['debug_query'] = 1;
   }else if($view->tag == 'latest_on_vibe_vixens') {
   		
   		$sql =  "SELECT /*latest_on_vibe*/ DISTINCT(node.nid) AS nid,
				   node_comment_statistics.comment_count AS node_comment_statistics_comment_count,
				   node.type AS node_type,
				   node.created AS node_created,
				   node_revisions.teaser AS node_revisions_teaser,
				   node_revisions.format AS node_revisions_format,
				   node.title AS node_title,
				   node_data_field_story_thumb.field_story_thumb_data AS node_data_field_story_thumb_field_story_thumb_data,
				   node_data_field_story_thumb.nid AS node_data_field_story_thumb_nid,
   				  node_data_field_story_thumb.field_excerpt_value AS node_data_field_story_thumb_field_excerpt_value,
				   node.vid AS node_vid,
				   node_data_field_story_thumb.field_story_thumb_fid AS node_data_field_story_thumb_field_story_thumb_fid,
				   node_data_field_story_thumb.field_story_thumb_list AS node_data_field_story_thumb_field_story_thumb_list,
				   node_revisions.body AS node_revisions_body,
				   node_data_field_img_src.field_img_src_fid AS node_data_field_img_src_field_img_src_fid,
				   node_data_field_img_src.field_img_src_list AS node_data_field_img_src_field_img_src_list,
				   node_data_field_img_src.field_img_src_data AS node_data_field_img_src_field_img_src_data,
				   jp_blog.base_uri AS jp_blog_base,
				   jp_blog.blog_type AS jp_blog_type,
				   jp_blog.celeb_image_path AS jp_blog_celeb_website_image,
				   jp_blog.name AS jp_blog_name

				 FROM 
				 	node node 				 
				 INNER JOIN
				 	term_node term_node ON node.vid = term_node.vid				 
				 INNER JOIN 
				 	node_comment_statistics node_comment_statistics ON node.nid = node_comment_statistics.nid
				 LEFT JOIN 
				 	jp_blog_node on jp_blog_node.nid = node.nid 
				 LEFT JOIN
				 	jp_blog on jp_blog.bid = jp_blog_node.bid
				 LEFT JOIN 
				 	node_revisions node_revisions ON node.vid = node_revisions.vid
				 LEFT JOIN 
				 	content_type_story node_data_field_story_thumb ON node.vid = node_data_field_story_thumb.vid
				 LEFT JOIN 
				 	content_field_img_src node_data_field_img_src ON node.vid = node_data_field_img_src.vid
				 WHERE 
				 	(node.type in ('advpoll_ranking', 'advpoll_binary', 'photo_gallery', 'audio', 'book', 'event', 'link', 'story', 'video')) 
				 AND 
				 	(term_node.tid = 4268) 
				 AND 
				 	(node.status <> 0)
				   
				 ORDER BY
				 	node_created DESC
";
					
   		$view->build_info['query'] =  $sql;
		//var_dump($view->build_info['query']);
   		$view->build_info['count_query'] = $sql;
   		$view->build_info['debug_query'] = 1;
   } else if($view->tag == 'latest_in_blogs'){
	   $sql =  "SELECT 
						/*latest in blogs*/ DISTINCT(node.nid) AS nid,
						node_comment_statistics.comment_count AS node_comment_statistics_comment_count,
						node.title AS node_title, 
						node.type AS node_type,  
						node.status AS node_status, 
						node.uid AS node_uid, 
						node_revisions.format AS node_revisions_format, 
						node_revisions.teaser AS node_revisions_teaser,
						node.changed AS node_changed,
						node.created AS node_created,
						node_revisions.body AS node_revisions_body,
						node_data_field_story_thumb.field_story_thumb_fid AS 																	node_data_field_story_thumb_field_story_thumb_fid,
						node_data_field_story_thumb.field_story_thumb_list AS node_data_field_story_thumb_field_story_thumb_list,
						node_data_field_story_thumb.field_story_thumb_data AS node_data_field_story_thumb_field_story_thumb_data,
	   node_data_field_story_thumb.nid AS node_data_field_story_thumb_nid,
						jp_blog.base_uri AS jp_blog_base,
						jp_blog.bid AS jp_blog_bid,
						jp_blog.name AS jp_blog_name,
						jp_blog.header_image_path AS jp_blog_image,
						jp_blog.celeb_image_path AS jp_blog_celeb_image_path,
						jp_blog.blog_type AS jp_blog_type,
						node_data_field_img_src.field_img_src_fid AS node_data_field_img_src_field_img_src_fid,
   node_data_field_img_src.field_img_src_list AS node_data_field_img_src_field_img_src_list,
   node_data_field_img_src.field_img_src_data AS node_data_field_img_src_field_img_src_data,
					  	term_data.name AS term_data_name
					FROM 
						{node} node
						
					INNER JOIN node_comment_statistics node_comment_statistics ON node.nid = node_comment_statistics.nid
	
					LEFT JOIN term_node term_node ON node.vid = term_node.vid 
	
					LEFT JOIN 
						{node_revisions} node_revisions ON node.vid = node_revisions.vid 
					LEFT JOIN 
						{jp_blog_node} jp_blog_node on jp_blog_node.nid = node.nid 
					LEFT JOIN
						jp_blog on jp_blog.bid = jp_blog_node.bid
					LEFT JOIN 
						content_type_story node_data_field_story_thumb ON node.vid = node_data_field_story_thumb.vid
					LEFT JOIN content_field_img_src node_data_field_img_src ON node.vid = node_data_field_img_src.vid
					LEFT JOIN term_data term_data ON term_node.tid = term_data.tid
					
					WHERE
					(node.type IN ('photo_gallery', 'audio', 'book', 'event', 'link', 'story', 'video'))
					AND
					(term_data.name = 'Blog')
					AND
					(node.status <> 0) 
					
					
					
					ORDER BY 
						node_changed DESC";
			$view->build_info['query'] =  $sql;
			$view->build_info['count_query'] = $sql;
			//drupal_set_message($view->build_info['query']); 
	}else if($view->tag == 'jpblog_header'){
	   $sql =  "SELECT 
						DISTINCT(node.nid) AS nid,
						jp_blog.base_uri AS jp_blog_base,
						jp_blog.name AS jp_blog_name,
						jp_blog.header_image_path AS jp_blog_image
					 FROM 
						{node} node
					 LEFT JOIN 
						{jp_blog_node} jp_blog_node on jp_blog_node.nid = node.nid 
					 LEFT JOIN
						jp_blog on jp_blog.bid = jp_blog_node.bid
						
					 WHERE 
					  jp_blog.bid = " . $blog_id . "  
					";
			$view->build_info['query'] =  $sql;
			$view->build_info['count_query'] = $sql;
			//drupal_set_message($view->build_info['query']); 
		}else if($view->tag == 'jpblog_website'){
	   $sql =  "SELECT 
						DISTINCT(node.nid) AS nid,
						jp_blog.celeb_image_path AS jp_blog_celeb_website_image,
						jp_blog.website_text AS jp_blog_website_text,
						jp_blog.celeb_link AS jp_blog_celeb_link,
						jp_blog.celeb_name_image_path AS jp_blog_celeb_name_image,
						jp_blog.editorial_image_path AS jp_blog_editorial_image_path,
						jp_blog.editorial_info AS jp_blog_editorial_info,
						jp_blog.blog_type AS jp_blog_blog_type
					 FROM 
						{node} node
					 LEFT JOIN 
						{jp_blog_node} jp_blog_node on jp_blog_node.nid = node.nid 
					 LEFT JOIN
						jp_blog on jp_blog.bid = jp_blog_node.bid	
					 WHERE 
					  jp_blog.bid = " . $blog_id . "  
					";
			$view->build_info['query'] =  $sql;
			$view->build_info['count_query'] = $sql;
			//drupal_set_message($view->build_info['query']); 
		}else if($view->tag == 'jpblog_editorial'){
	   $sql =  "SELECT 
						DISTINCT(node.nid) AS nid,
						jp_blog.editorial_image_path AS jp_blog_editorial_image_path,
						jp_blog.editorial_info AS jp_blog_editorial_info
					 FROM 
						{node} node
					 LEFT JOIN 
						{jp_blog_node} jp_blog_node on jp_blog_node.nid = node.nid 
					 LEFT JOIN
						jp_blog on jp_blog.bid = jp_blog_node.bid	
					 WHERE 
					  jp_blog.bid = " . $blog_id . "  
					";
			$view->build_info['query'] =  $sql;
			$view->build_info['count_query'] = $sql;
			//drupal_set_message($view->build_info['query']); 
		}else if($view->tag == 'top_celeb_bloggers'){
	   $sql =  "SELECT
	   					DISTINCT(node.nid) AS nid,
	   					jp_blog.bid AS jp_blog_bid,
						jp_blog.name AS jp_blog_name,
						jp_blog.header_image_path AS jp_blog_header_image_path,
						jp_blog.celeb_website_image_path AS jp_blog_celeb_image_path,
						jp_blog.celeb_name AS jp_blog_celeb_name,
						jp_blog.base_uri AS jp_blog_base,
						jp_blog.blog_type AS jp_blog_type
						   					
				FROM 
					{node} node
				 LEFT JOIN 
					{jp_blog_node} jp_blog_node on jp_blog_node.nid = node.nid 
				 LEFT JOIN
					jp_blog on jp_blog.bid = jp_blog_node.bid
				WHERE 
					jp_blog.blog_type = 1
					AND
					jp_blog.top_celeb_blog = 1
				GROUP BY
					jp_blog.bid  
				ORDER BY 
					jp_blog.bid DESC";
			$view->build_info['query'] =  $sql;
			$view->build_info['count_query'] = $sql;
			//drupal_set_message($view->build_info['query']); 
		}else if($view->tag == 'related_by_terms') {
			$sql = "SELECT node.nid AS nid,
					   node.title AS node_title,
					   term_data.name AS term_data_name,
					   term_data.vid AS term_data_vid,
					   term_data.tid AS term_data_tid
					 FROM node node 
					 LEFT JOIN term_node term_node ON node.vid = term_node.vid
					 INNER JOIN term_data term_data ON term_node.tid = term_data.tid
					 WHERE term_data.name IN ".$terms."
					";
			$view->build_info['query'] =  $sql;
			$view->build_info['count_query'] = $sql;	

		
		
		}
}

