<?php
// $Id: imagecrop.module,v 1.1.4.16 2009/06/04 14:01:44 longwave Exp $

/**
 * @file
 * Provides a javascript toolbox through an imagecache action.
 *
 * @author Kristof De Jaeger - http://drupal.org/user/107403 - http://realize.be
 * @version this is the drupal 6.x version
 */

/**
 * Implementation of hook_perm().
 */
function imagecrop_perm() {
  return array('crop images with toolbox', 'administer imagecrop');
}

/**
 * Implementation of hook_menu().
 */
function imagecrop_menu() {
  $items = array();

  $items['admin/settings/imagecrop'] = array(
    'title' => 'Imagecache javascript crop',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('imagecrop_settings'),
    'access arguments' => array('administer imagecrop'),
  );
  $items['imagecrop/showcrop'] = array(
    'page callback' => 'imagecrop_showcrop',
    'type' => MENU_CALLBACK,
    'access arguments' => array('crop images with toolbox'),
  );
  $items['imagecrop/docrop'] = array(
    'page callback' => 'imagecrop_docrop',
    'type' => MENU_CALLBACK,
    'access arguments' => array('crop images with toolbox'),
  );

  return $items;
}

/**
 * Implementation of hook_theme().
 */
function imagecrop_theme() {
  return array(
    'imagecrop_javascript' => array(
      'arguments' => array('element' => NULL),
    ),
    'imagecrop' => array(
      'arguments' => array('url' => NULL, 'width' => NULL, 'height' => NULL, 'resize' => NULL),
    ),
    'imagecrop_result' => array(
      'arguments' => array('presetname' => NULL, 'filepath' => NULL, 'alt' => NULL, 'attributes' => NULL),
    ),
    'presettabs' => array(
      'arguments' => array('presets' => array(), 'fid' => NULL, 'presetid' => NULL, 'module' => NULL, 'field' => NULL),
    ),
  );
}

/**
 * Implementation of hook_theme_registry_alter().
 */
function imagecrop_theme_registry_alter(&$theme_registry) {
  array_unshift($theme_registry['page']['theme paths'], drupal_get_path('module', 'imagecrop'));
}

/**
 * Imagecrop settings page
 */
function imagecrop_settings() {
  // hook into image module
  if (module_exists('image')) {
    $options_modules['image'] = t('Hook into image module');
  }
  // hook into node_images module
  if (module_exists('node_images')) {
    $result = db_query("SELECT name,value FROM {variable} WHERE name LIKE 'node_images_position_%'");
    if ($result) {
      drupal_set_message(t('When you want to enable support for the node_images module, please read the README that comes with the imagecrop module.'));
      while ($row = db_fetch_object($result)) {
        if (variable_get($row->name, 'hide') != 'hide') {
          $explode = explode('_', $row->name);
          $options_modules[$row->name] = t('Hook into node_images module for <em>content type @type</em>', array('@type' => $explode[3]));
        }
      }
    }
  }
  // show checkboxes if options are not empty
  if (!empty($options_modules)) {
    $form['imagecrop_modules'] = array(
      '#type' => 'checkboxes',
      '#title' => t('Hook into modules'),
      '#default_value' => variable_get('imagecrop_modules', array()),
      '#options' => $options_modules,
    );
    $form['array_filter'] = array('#type' => 'hidden');
  }
  else {
    $form['no_modules_fields'] = array(
      '#type' => 'item',
      '#value' => t('No supported modules were found to hook into.'),
    );
  }

  if (module_exists('imagefield')) {
    $form['imagefield'] = array(
      '#type' => 'item',
      '#value' => t('Imagecrop settings for CCK Imagefields are found on the field configuration pages.'),
    );
  }

  $popups = array('basic' => t('Basic popup window'));
  if (module_exists('thickbox')) {
    $popups['thickbox'] = t('Thickbox');
  }
  
  $form['imagecrop_popup'] = array(
    '#type' => 'radios',
    '#title' => t('Popup window type'),
    '#default_value' => variable_get('imagecrop_popup', 'basic'),
    '#options' => $popups,
  );
  
  $form['imagecrop_popup_width'] = array(
    '#type' => 'textfield',
    '#title' => t('Popup window width'),
    '#default_value' => variable_get('imagecrop_popup_width', 700),
    '#size' => 4,
    '#field_suffix' => 'pixels',
  );
  
  $form['imagecrop_popup_height'] = array(
    '#type' => 'textfield',
    '#title' => t('Popup window height'),
    '#default_value' => variable_get('imagecrop_popup_height', 600),
    '#size' => 4,
    '#field_suffix' => 'pixels',
  );
  
  $form['imagecrop_scale_step'] = array(
    '#type' => 'textfield',
    '#title' => t('Step size for scale dropdown'),
    '#default_value' => variable_get('imagecrop_scale_step', 50),
    '#size' => 4,
    '#field_suffix' => 'pixels',
  );
  
  // drupal message if no action is found with javascript_crop
  if (imagecrop_action_exists() == FALSE) {
    drupal_set_message(t('No preset is found with the javascript_crop action so far. If you want to take advantage of this module, you will need to create at least one preset with that action.'));
  }
  return system_settings_form($form);
}

/**
 * Implementation of hook_cron().
 * Delete all references in imagecrop table when
 *   a) file doesn't exist anymore.
 *   b) when preset has been deleted.
 *   c) when javascrip_crop action is removed from a preset.
 */
function imagecrop_cron() {
  // get all files which do not exist anymore from the files table
  $result = db_query("SELECT ic.fid,ic.presetid FROM {imagecrop} ic WHERE NOT EXISTS (SELECT fid FROM {files} f WHERE ic.fid = f.fid) AND ic.reference = 'files'");
  while ($row = db_fetch_object($result)) {
    $records[] = array('fid' => $row->fid, 'presetid' => $row->presetid, 'reference' => 'files');
  }
  // get all files which do not exist anymore from the node_images table
  if (module_exists('node_images')) {
    $result = db_query("SELECT ic.fid,presetid FROM {imagecrop} ic WHERE NOT EXISTS (SELECT id FROM {node_images} ni WHERE ic.fid = ni.id) AND ic.reference = 'node_images'");
    while ($row = db_fetch_object($result)) {
      $records[] = array('fid' => $row->fid, 'presetid' => $row->presetid, 'reference' => 'node_images');
    }
  }
  /*
   * Get all records
   *  a) from presets which do not exist anymore.
   *  b) and/or from presets with no imagecrop_javascript action anymore.
   */
  // files table
  $result = db_query("SELECT ic.fid,ic.presetid FROM {imagecrop} ic WHERE NOT EXISTS (SELECT presetid FROM {imagecache_action} ia where ic.presetid = ia.presetid AND ia.action = 'imagecrop_javascript') AND ic.reference = 'files'");
  while ($row = db_fetch_object($result)) {
    $records[] = array('fid' => $row->fid, 'presetid' => $row->presetid, 'reference' => 'files');
  }
  // node_images table
  if (module_exists('node_images')) {
    $result = db_query("SELECT ic.fid,ic.presetid FROM {imagecrop} ic WHERE NOT EXISTS (SELECT presetid FROM {imagecache_action} ia where ic.presetid = ia.presetid AND ia.action = 'imagecrop_javascript') AND ic.reference = 'node_images'");
    while ($row = db_fetch_object($result)) {
      $records[] = array('fid' => $row->fid, 'presetid' => $row->presetid, 'reference' => 'node_images');
    }
  }
  if (!empty($records)) {
    while (list($key, $val) = each($records)) {
      db_query("DELETE FROM {imagecrop} WHERE fid=%d AND presetid=%d AND reference = '%s'", $val['fid'], $val['presetid'], $val['reference']);
    }
  }
}

/**
 * Implementation of hook_imagecache_actions().
 */
function imagecrop_imagecache_actions() {
  $actions = array(
    'imagecrop_javascript' => array(
      'name' => 'Javascript crop',
      'description' => 'Create a crop with a javascript toolbox.',
      'file' => 'imagecrop_actions.inc',
    ),
  );
  return $actions;
}

/**
 * Helper function to check if a preset exists with the imagecrop_javascript action.
 * Needed to determine if we have to display our javascript crop link.
 *
 * @return true or false
 */
function imagecrop_action_exists() {
  $result = db_result(db_query("SELECT actionid FROM {imagecache_action} WHERE action = 'imagecrop_javascript'"));
  return $result;
}

/**
 * Hook into CCK field forms for imagefield configuration.
 */
function imagecrop_form_content_field_edit_form_alter(&$form, $form_state) {
  if ($form['#field']['widget']['module'] == 'imagefield' && user_access('administer imagecrop')) {
    $field = $form['#field']['field_name'];
    $presets = array();
    foreach (imagecache_presets() as $preset) {
      foreach ($preset['actions'] as $action) {
        if ($action['action'] == 'imagecrop_javascript') {
          $presets[$preset['presetname']] = $preset['presetname'];
        }
      }
    }
    $field_presets = variable_get('imagecrop_field_presets', array());

    $form['field']['imagecrop'] = array(
      '#type' => 'fieldset',
      '#title' => t('Imagecrop settings'),
      '#weight' => 1,
    );
    if (count($presets)) {
      $form['field']['imagecrop']['imagecrop_enable'] = array(
        '#type' => 'checkbox',
        '#title' => t('Enable JavaScript image crop tool for this field.'),
        '#default_value' => in_array($field, variable_get('imagecrop_fields', array())),
      );
      $form['field']['imagecrop']['imagecrop_field_presets'] = array(
        '#type' => 'checkboxes',
        '#title' => t('Enable JavaScript image crop tool for these Imagecache presets.'),
        '#description' => t('Select the Imagecache presets that will be used with this field'),
        '#default_value' => isset($field_presets[$field]) ? $field_presets[$field] : array(),
        '#options' => $presets,
      );
      $form['#submit'][] = 'imagecrop_form_content_field_edit_form_submit';
    }
    else {
      $form['field']['imagecrop']['imagecrop_warning'] = array(
        '#value' => t('No preset is found with the javascript_crop action so far. If you want to take advantage of this module, you will need to create at least one preset with that action.'),
      );
    }
  }
}

function imagecrop_form_content_field_edit_form_submit($form, &$form_state) {
  $field = $form_state['values']['field_name'];
  $fields = array_diff(variable_get('imagecrop_fields', array()), array($field));
  if ($form_state['values']['imagecrop_enable']) {
    $fields[] = $field;
  }
  variable_set('imagecrop_fields', $fields);
  
  $presets = variable_get('imagecrop_field_presets', array());
  $presets[$field] = array_keys(array_filter($form_state['values']['imagecrop_field_presets']));
  variable_set('imagecrop_field_presets', $presets);
}

/**
 * Implementation of hook_form_alter().
 * Hook into several existing image modules/fields.
 */
function imagecrop_form_alter(&$form, $form_state, $form_id) {
  // do we have presets with javascript_crop ?
  $exists = imagecrop_action_exists();
  // user access
  $access = user_access('crop images with toolbox');
  // build array with available modules/fields
  $modules = variable_get('imagecrop_modules', array());
  $fields = variable_get('imagecrop_fields', array());
  $hooks = array_merge($modules, $fields);

  // hook into imagefield module
  if (module_exists('imagefield') && $exists != FALSE && $access) {
    foreach (imagecrop_find_imagefields($form, $fields) as $field) {
      foreach (element_children($form[$field]) as $i) {
        if ($form[$field][$i]['#default_value']['fid']) {
          $form[$field][$i]['#description'] = imagecrop_linkitem($form[$field][$i]['#default_value']['fid'], 'imagefield', $field);
        }
        else {
          $form[$field][$i]['#description'] = t('You will be able to crop this image after clicking Save.');
        }
      }
    }
  }

  // hook into image module
  if (module_exists('image') && $exists != FALSE && $access && in_array('image', $hooks) && isset($form['images']['thumbnail'])) {
    // it's anonying we have to make a database call to get the right fid.
    $fid = db_result(db_query("SELECT i.fid FROM {image} i LEFT JOIN {files} f on f.fid = i.fid WHERE i.nid=%d AND filepath='%s' AND filename = '_original'", $form['nid']['#value'], $form['images']['_original']['#value']));
    $form['croptab'] = imagecrop_formitem($fid, -10);
  }

  // hook into node_images module
  if (module_exists('node_images') && $form_id == '_node_images_list' && $exists != FALSE && $access) {
    $type = $form['#parameters'][1]->type;
    if (variable_get('node_images_position_'. $type, 'hide') != 'hide' && in_array('node_images_position_'. $type, $hooks)) {
      $form['imagecrop'] = array('#type' => 'hidden', '#value' => '1');
    }
  }
}

/**
 * Helper function to add form item
 *
 * @return $form form markup
 */
function imagecrop_formitem($fid, $weight = 0) {
  return array(
    '#type' => 'item',
    '#value' => imagecrop_linkitem($fid),
    '#weight' => $weight,
  );
}

/**
 * Helper function to add click link
 *
 * @return $form form markup
 */
function imagecrop_linkitem($fid, $module = '', $field = '') {
  $popup = variable_get('imagecrop_popup', 'basic');
  $width = variable_get('imagecrop_popup_width', 700);
  $height = variable_get('imagecrop_popup_height', 600);
  
  $module = $module ? ('/0/'. $module) : '';
  $field = $field ? ('/'. $field) : '';
  $url = url('imagecrop/showcrop/'. $fid . $module . $field, array('absolute' => TRUE));

  if ($popup == 'thickbox' && module_exists('thickbox')) {
    return '<a class="thickbox" href="'. $url .'?KeepThis=true&TB_iframe=true&height='. $height .'&width='. $width .'">'. t('Crop this image') .'</a>';
  }
  else {
    return '<a href="javascript:;" onclick="window.open(\''. $url .'\',\'imagecrop\',\'menubar=0,scrollbars=1,resizable=1,width='. $width .',height='. $height .'\');">'. t('Crop this image') .'</a>';
  }
}

/**
 * Helper function to search for a cck field image.
 * Temporary images not supported at this point.
 *
 * @param $form complete form object
 * @param $fields all available fields from settings
 * @return ckk imagefields array or false
 */
function imagecrop_find_imagefields($form, $fields) {
  $return = array();
  $temp_path = file_directory_temp();
  foreach ($fields as $field) {
    $temppath = strpos($form[$field][0]['filepath']['#value'], $temp_path);
    $deleteflag = $form[$field][0]['flags']['delete']['#value'];
    if (isset($form[$field]) && $temppath === FALSE && $deleteflag != 1) {
      $return[] = $field;
    }
  }
  return $return;
}

/**
 * Callback with javascript crop.
 *
 * @param $fid id of file
 * @param $presetid id of preset
 */
function imagecrop_docrop($fid, $presetid, $module = '', $field = '') {
  imagecrop_markup(TRUE, TRUE);
  if (imagecrop_action_exists() == TRUE) {
    $presets = return_presets($presetid, $module, $field);
    $file = create_image_object($fid, $presetid, $module);
    if ($file != FALSE) {
      $size_warning = FALSE;
      // get size of temporary image
      $size = getimagesize($file->dst);
      $width = $size[0];
      $height = $size[1];
      // return warning message if crop toolbox is too big and not resizable.
      if (($width < $file->crop_width || $height < $file->crop_height) && $file->resizable == 0) {
        $size_warning = FALSE;
      }

      // add jquery ui
      if ($file->resizable)
      jquery_ui_add(array('ui.resizable', 'ui.draggable', 'effects.scale'));
      else
      jquery_ui_add(array('ui.draggable'));

      // output
      if ($size_warning == FALSE) {
        $url = file_create_url($file->dst) .'?time='. time();
        $output = theme('presettabs', $presets, $fid, $presetid, $module, $field);
        $output .= '<div id="imagecrop_help">'. t('To save the selected crop area, click the Save button.') .'</div>';
        $output .= theme('imagecrop', $url, $width, $height, $file->resizable);
        $output .= drupal_get_form('imageoffsets', $file->xoffset, $file->yoffset, $file->crop_width, $file->crop_height, $presetid, $fid, $module, $field, $file->orig_width, $file->orig_height, $file->scale);
      }
      else {
        $output .= '<div id="imagecrop_info" class="imagecrop_error">'. t('The crop toolbox is too big for this image.') .' <a href="javascript:history.back();"><span class="white">'. t('Back') .'</span></a></div>';
      }
      return $output;
    }
    else {
      return '<div id="imagecrop_info" class="imagecrop_error">'. t('Image to crop was not found.') .'</div>';
    }
  }
  else {
    return '<div id="imagecrop_info"  class="imagecrop_error">'. t('No preset is found with the javascript_crop action so far. If you want to take advantage of this module, you will need to create at least one preset with that action.') .'</div>';
  }
}

/**
 * Callback to return offsets, height & width
 *
 * @param $xoffset x value of javascript box
 * @param $yoffset y value of javascript box
 * @param $crop_width width of javascript box
 * @param $crop_height height of javascript box
 * @param $presetid id of preset
 * @param $fid id of file
 * @param $module specific module
 * @return array $form
 */
function imageoffsets(&$form_state, $xoffset, $yoffset, $crop_width, $crop_height, $presetid, $fid, $module, $field, $width, $height, $scale) {
  $step = variable_get('imagecrop_scale_step', 50);
  $aspect = $width / $height;
  $options['original'] = $width .' x ' . $height .'px (Original)';
  $width -= $step;
  while ($width > $crop_width && ($width / $aspect) > $crop_height) {
    $options[$width] = $width .' x '. intval($width / $aspect) .'px';
    $width -= $step;
  }

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
    '#prefix' => '<table id="imagecrop_table_actions"><tr><td>',
    '#suffix' => '</td>',
  );
  $form['scaling'] = array(
    '#type' => 'select',
    '#options' => $options,
    '#default_value' => $scale,
    '#prefix' => '<td id="imagecrop-throbber">',
    '#suffix' => '</td></tr></table>',
    '#attributes' => array('onchange' => "$('#imagecrop-throbber').addClass('show'); $('#edit-scaledown').click();"),
  );
  $form['scaledown'] = array(
    '#type' => 'submit',
    '#value' => t('Scale image'),
    '#attributes' => array('style' => "display:none;"),
  );
  $form['image-crop-x'] = array(
    '#type' => 'hidden',
    '#default_value' => $xoffset,
    '#attributes' => array('class' => 'edit-image-crop-x'),
  );
  $form['image-crop-y'] = array(
    '#type' => 'hidden',
    '#default_value' => $yoffset,
    '#attributes' => array('class' => 'edit-image-crop-y'),
  );
  $form['image-crop-width'] = array(
    '#type' => 'hidden',
    '#default_value' => $crop_width,
    '#attributes' => array('class' => 'edit-image-crop-width'),
  );
  $form['image-crop-height'] = array(
    '#type' => 'hidden',
    '#default_value' => $crop_height,
    '#attributes' => array('class' => 'edit-image-crop-height'),
  );
  $form['fid'] = array(
    '#type' => 'hidden',
    '#value' => $fid,
  );
  $form['module'] = array(
    '#type' => 'hidden',
    '#value' => $module,
  );
  $form['field'] = array(
    '#type' => 'hidden',
    '#value' => $field,
  );
  $form['presetid'] = array(
    '#type' => 'hidden',
    '#value' => $presetid,
  );

  return $form;
}

/**
 * Save the offset & size values
 *
 * @param $form_id id of the form
 * @param $form_values submitted values of the imageoffsets form
 */
function imageoffsets_submit($form, &$form_state) {
  if ($form_state['values']['op'] == t('Scale image')) {
    $form_state['values']['image-crop-x'] = 0;
    $form_state['values']['image-crop-y'] = 0;
  }
  $module = (!empty($form_state['values']['module'])) ? '/'. $form_state['values']['module'] : '';
  $field = (!empty($form_state['values']['field'])) ? '/'. $form_state['values']['field'] : '';
  $reference = $form_state['values']['module'] == 'node_images' ? 'node_images' : 'files';
  db_query("DELETE FROM {imagecrop} WHERE fid=%d AND presetid=%d AND reference = '%s'", $form_state['values']['fid'], $form_state['values']['presetid'], $reference);
  db_query("INSERT INTO {imagecrop} VALUES (%d,%d,'%s',%d,%d,%d,%d,'%s')", $form_state['values']['fid'], $form_state['values']['presetid'], $reference, $form_state['values']['image-crop-x'], $form_state['values']['image-crop-y'], $form_state['values']['image-crop-width'], $form_state['values']['image-crop-height'], $form_state['values']['scaling']);
  if ($form_state['values']['op'] == t('Scale image'))
    drupal_goto('imagecrop/docrop/'. $form_state['values']['fid'] .'/'. $form_state['values']['presetid'] . $module . $field);
  else
    drupal_goto('imagecrop/showcrop/'. $form_state['values']['fid'] .'/'. $form_state['values']['presetid'] . $module . $field);
}


/**
 * Show the cropped image.
 *
 * @param $fid file id
 * @param $presetid id of preset
 * @return cropped version of chosen image
 */
function imagecrop_showcrop($fid, $presetid = 0, $module = '', $field = '') {
  imagecrop_markup(FALSE, TRUE);
  if (imagecrop_action_exists() == TRUE) {
    $presets = return_presets($presetid, $module, $field);
    $presetid = $presets['presetid'];
    $file = create_image_object($fid, $presetid, $module, TRUE);
    if ($file != FALSE) {
      $output = theme('presettabs', $presets, $fid, $presetid, $module, $field);
      $module = (!empty($module)) ? '/'. $module : '';
      $field = (!empty($field)) ? '/'. $field : '';
      $output .= '<div id="imagecrop_help">'. l(t('Click here to choose another crop area for this picture'), 'imagecrop/docrop/'. $fid .'/'. $presetid . $module . $field) .'</div>';
      $output .= theme('imagecrop_result', $file->presetname, $file->filepath);
      return $output;
    }
    else {
      return '<div id="imagecrop_info" class="imagecrop_error">'. t('Image to crop was not found.') .'</div>';
    }
  }
  else {
    return '<div id="imagecrop_info"  class="imagecrop_error">'. t('No preset is found with the javascript_crop action so far. If you want to take advantage of this module, you will need to create at least one preset with that action.') .'</div>';
  }
}

/**
 * Helper function to determine which preset exists and which to load
 *
 * @param $presetid id of preset
 * @return $presets array with presetid to load and list of all other possible presets
 */
function return_presets($presetid, $module = '', $field = '') {
  $filter = array();
  if ($module == 'imagefield' && $field) {
    $field_presets = variable_get('imagecrop_field_presets', '');
    if (isset($field_presets[$field])) {
      $filter = $field_presets[$field];
    }
  }

  $result = db_query("SELECT ip.presetid, ip.presetname FROM {imagecache_preset} ip INNER JOIN {imagecache_action} ia on ia.presetid = ip.presetid WHERE action = 'imagecrop_javascript' ORDER by ip.presetname ASC");
  while ($row = db_fetch_object($result)) {
    if (!count($filter) || in_array($row->presetname, $filter)) {
      $presets['tabs'][] = array('id' => $row->presetid, 'name' => $row->presetname);
      if ($presetid == $row->presetid) {
        $presets['presetid'] = $presetid;
      }
    }
  }
  if (!isset($presets['presetid'])) {
    $presets['presetid'] = $presets['tabs'][0]['id'];
  }
  return $presets;
}

/**
 * Helper function to create image
 *
 * @param $fid file id in files table
 * @param $presetid id of the preset
 * @param $cutoff delete the javascript crop action when user wants to define the offsets
 * @return $file with file, javascript crop and preset properties
 */
function create_image_object($fid, $presetid, $module = '', $cutoff = FALSE) {
  $file = _imagecrop_file_load($fid, $module);
  if ($file != FALSE) {
    $preset = imagecache_preset($presetid);
    imagecache_image_flush($file->filename);
    if ($cutoff == FALSE) {
      // get the actions from the preset and and throw out the javascript_crop action
      // and every other action which comes after it.
      $break = FALSE;
      while (list($key, $val) = each($preset['actions'])) {
        if ($val['action'] == 'imagecrop_javascript') {
          $crop_width = $preset['actions'][$key]['data']['width'];
          $crop_height = $preset['actions'][$key]['data']['height'];
          $resizable = $preset['actions'][$key]['data']['resizable'];
          $break = TRUE;
        }
        if ($break == TRUE) {
          unset($preset['actions'][$key]);
        }
      }
      // see if we have stored values allready for this file
      $file->xoffset = 0;
      $file->yoffset = 0;
      $file->crop_width = $crop_width;
      $file->crop_height = $crop_height;
      $reference = $module == 'node_images' ? 'node_images' : 'files';
      $row = db_fetch_object(db_query("SELECT xoffset,yoffset,width,height,scale FROM {imagecrop} ic where ic.fid = %d AND ic.presetid = %d AND ic.reference = '%s'", $fid, $presetid, $reference));
      $firstscale = FALSE;
      if (!empty($row)) {
        $file->xoffset = $row->xoffset;
        $file->yoffset = $row->yoffset;
        $file->crop_width = $row->width;
        $file->crop_height = $row->height;
        $file->scale = $row->scale;
        $firstscale = TRUE;
      }
      // resizable or not
      $file->resizable = $resizable;

      // add scale action if necessary
      if ($row->scale != 'original' && $firstscale == TRUE) {
        $preset['actions'][] = array(
          'action' => 'imagecache_scale',
          'data' => array('width' => $row->scale, 'height' => '', 'upscale' => 'false'));
      }
    }
    $src = $file->filepath;
    $file->presetname = $preset['presetname'];
    $dst = imagecache_create_path($cutoff ? $preset['presetname'] : '_imagecrop_temp', $file->filepath);
    $file->dst = $dst;

    // original size
    $orig = getimagesize($file->filepath);
    $file->orig_width = $orig[0];
    $file->orig_height = $orig[1];

    // create the file to display for the crop,
    // we also set a global presetid variable, so I can use this in
    // the javascript_crop action
    $GLOBALS['imagecrop_presetid'] = $presetid;
    imagecache_build_derivative($preset['actions'], $src, $dst);
    return $file;
  }
  else return FALSE;
}

/**
 * Helper function to load a file into an object
 *
 * @param $fid file id
 * @param $module specific module which does not use the files table
 * @return $file with properties of the file or false
 */
function _imagecrop_file_load($fid, $module) {
  global $user;

  if (empty($module) || $module == 'imagefield') {
    $file = db_fetch_object(db_query('SELECT * FROM {files} WHERE fid = %d', $fid));
  }
  else if ($module == 'node_images') {
    $file = db_fetch_object(db_query('SELECT * FROM {node_images} WHERE id = %d', $fid));
  }

  if ($file) {
    // make sure it's an image. Any other mime extensions possible?
    // return false if it's not the right mime type
    $filemime = array('image/jpeg', 'image/gif', 'image/png', 'image/pjpeg');
    if (!in_array($file->filemime, $filemime)) return FALSE;
    // access denied if current user hasn't enough permissions
    if (!user_access('administer nodes') && $user->uid != $file->uid) {
      drupal_access_denied();
      exit();
    }
    // all seems ok, return file
    return $file;
  }
  // return false if no file was found.
  return FALSE;
}

/**
 * Theme image crop.
 *
 * @param $url url of image
 * @param $width width of image
 * @param $height height of image
 * @param $resize wether the cropping box is resizeble or not
 * @return $output html of the javascript crop area
 */
function theme_imagecrop($url, $width, $height, $resize = 0) {
  $output = '
    <div style="margin-left: 3px;"><div class="imagefield-crop-wrapper" id="imagefield-crop-wrapper" style="position: absolute; margin-top:60px; width: '. $width .'px; height: '. $height .'px;">
      <div id="image-crop-container" style="background-image: url(\''. $url .'\'); width:'. $width  .'px; height:'. $height  .'px;"></div>
      <div id="resizeMe" style="background-image: url(\''. $url .'\'); width:'. $width  .'px; height:'. $height  .'px; top: 20px;">';
  $output .= '</div></div></div><div style="clear:both;"></div>';

  return $output;
}

/**
 * Theme cropped image result. Adds time to the image so we make sure
 * the brower always loads the latest version of the image.
 *
 * @param string $presetname
 * @param string $filepath
 * @param string $alt
 * @param string $attributes
 * @return image
 */
function theme_imagecrop_result($presetname, $filepath, $alt = '', $attributes = NULL) {
  $url = imagecache_create_url($presetname, $filepath);
  return '<img src="'. $url .'?time='. time() .'" alt="'. check_plain($alt) .'" title="'. check_plain($alt) .'" '. $attributes .' />';
}

/**
 * Theme preset tabs
 *
 * @param $tabs array of available presets
 * @param fid file id
 * @param $presetid preset to highlight
 * @return $output html of the tabs
 */
function theme_presettabs($presets, $fid, $presetid, $module = '', $field = '') {
  $module = $module ? ('/'. $module) : '';
  $field = $field ? ('/'. $field) : '';
  $tab_output = '';
  foreach ($presets['tabs'] as $key => $value) {
    $class = ($value['id'] == $presetid) ? 'imagecrop_tab imagecrop_highlight' : 'imagecrop_tab ';
    $url = 'imagecrop/showcrop/'. $fid .'/'. $value['id'] . $module . $field;
    $tab_output .= '<span class="'. $class .'">'. l($value['name'], $url) .'</span>';
  }
  $output = '<div id="imagecrop_presettabs">'. t('Image presets &raquo;') .' '. $tab_output .'</div>';
  return $output;
}

/**
 * Add imagecrop css & javascript
 */
function imagecrop_markup($js, $css) {
  $path = drupal_get_path('module', 'imagecrop');
  if ($js == TRUE) drupal_add_js($path .'/imagecrop.js');
  if ($css == TRUE) drupal_add_css($path .'/imagecrop.css');
}
