<?php

function jetpack_imagecache_actions() {
	$actions = array(
		'jetpack_imagecache_scale_and_crop' => array(
      		'name' => 'Jetpack Scale And Crop',
      		'description' => 'Jetpack version of Scale and Crop',
    	),
	);
	
	return $actions;
}

function jetpack_imagecache_theme() {
	return array(
		'jetpack_imagecache_scale_and_crop' => array(
      		'arguments' => array('element' => NULL),
		),
	);
}

function jetpack_imagecache_scale_and_crop_form($action) {
   $form['width'] = array(
    '#type' => 'textfield',
    '#title' => t('Width'),
    '#default_value' => isset($action['width']) ? $action['width'] : '100%',
    '#description' => t('Enter a width in pixels or as a percentage. i.e. 500 or 80%.'),
  );
  $form['height'] = array(
    '#type' => 'textfield',
    '#title' => t('Height'),
    '#default_value' => isset($action['height']) ? $action['height'] : '100%',
    '#description' => t('Enter a height in pixels or as a percentage. i.e. 500 or 80%.'),
  );
  return $form;
}

function jetpack_imagecache_scale_and_crop_image(&$image, $data) {
  $scale = max($data['width'] / $image->info['width'], $data['height'] / $image->info['height']);
  $x = ($image->info['width'] * $scale - $data['width']) / 2;
  $y = 0; //($image->info['height'] * $scale - $height) / 2;

  if (imageapi_image_resize($image, $image->info['width'] * $scale, $image->info['height'] * $scale)) {
    if (imageapi_image_crop($image, $x, $y, $data['width'], $data['height'])) {
    	return TRUE;
    }
  }
  watchdog('jetpack_imagecache', 'jetpack_imagecache_scale_and_crop failed. image: %image, data: %data.', array('%image' => $image->source, '%data' => print_r($data, TRUE)), WATCHDOG_ERROR);
  return FALSE;
}

function theme_jetpack_imagecache_scale_and_crop($element) {
   $data = $element['#value'];
  if ($data['width'] && $data['height']) {
    return check_plain($data['width']) . 'x' . check_plain($data['height']);
  }
  return ($data['width']) ? t('width @width', array('@width' => $data['width'])) : t('height @height', array('@height' => $data['height']));

}