<?php
// $Id$

/*
 * Implementation of hook_block()
 */

function facebook_recommend_block($op = 'list', $delta = 0, $edit = array()) {
	switch($op) {
		case 'list':
			$blocks[0]['info'] = t('Facebook recommend block');
			return $blocks;

		case 'configure':
			$form['facebook_recommend_block_options']['face_setting'] = array(
				'#type' => 'radios',
				'#title' => t('Show faces'),
				'#default_value' => variable_get('face_setting', 0),
				'#options' => array(t('Yes'), t('No')),
			);
			$form['facebook_recommend_block_options']['like_recommend_setting'] = array(
				'#type' => 'radios',
				'#title' => t('Like or Recommend button'),
				'#default_value' => variable_get('like_recommend_setting', 0),
				'#options' => array(t('Recommend'), t('Like')),
			);
			return $form;

		case 'save':
			variable_set('face_setting', $edit['face_setting']);
			variable_set('like_recommend_setting', $edit['like_recommend_setting']);
			break;

		case 'view':
			global $base_url;

			$faces = variable_get('face_setting', 0);
			if($faces) {
				$faces = 'false';
			}
			else {
				$faces = 'true';
			}

			$like_recommend = variable_get('like_recommend_setting', 0);
			if($like_recommend) {
				$like_recommend = 'like';
			}
			else {
				$like_recommend = 'recommend';
			}

			$tempURL = implode(arg(), "/");
			$url = $base_url.'/'.urlencode(drupal_get_path_alias($tempURL));

			$link = t('<iframe src="http://www.facebook.com/plugins/like.php?href='.$url.'
				&amp;layout=standard&amp;show_faces='.$faces.'&amp;width=450&amp;action='.$like_recommend.'
				&amp;colorscheme=light"scrolling="no" frameborder="0" allowTransparency="true"
				style="border:none; overflow:hidden; width:450px; height:60px"></iframe>');

			$block['subject'] = t('');
			$block['content'] = theme('facebook_recommend', $link);
			return $block;
	}
}

function facebook_recommend_theme() {
	return array('facebook_recommend' => array(
		'arguments' => array(
			$link => NULL)
		)
	);
}


function theme_facebook_recommend($link) {
	$output = '<div class="facebook_recommend">'.$link.'</div>';
	return $output;
}