<?php
// $Id: glossify.module,v 1.1.2.23 2010/02/23 11:37:18 rsvelko Exp $
 


/**
 * Implementation of hook_menu().
 */
function glossify_menu() {
  $items['admin/settings/glossify'] = array(
    'title' => 'Glossify',
    'description' => 'Manipulate glossify behaviour',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('glossify_admin_settings'),
    'access arguments' => array('administer glossify'),
  );
  return $items;
}


/**
 * This procedure gathers all link-to terms into an array that is made global.
 * It has node-titles as its keys and nids as values.
 * It is sorted by strlen of the keys(titles).
 */

function _glossify_build_dictionary_of_link_to_terms() {
  global $glossify_dict;
  global $glossify_dict_titles;

  if (!empty($glossify_dict) ) { return; }

  $content_types_that_give_terms = variable_get('glossify_glossary_content_type', NULL);
  
  // return if no nodetypes that hold terms
  if (!isset($content_types_that_give_terms)) {
    return;
  }

  
  // build WHERE clause
  foreach ($content_types_that_give_terms as $type) {
    $clause_parts[] = "type='$type' ";
    $clause_parts_with_name[] = "type_name='$type' ";
  }
  
  $where_clause = implode(' OR ', $clause_parts);
  $where_clause_with_name = implode(' OR ', $clause_parts_with_name);
  // WHERE clause ready
  
  
  
  
  
  // for target cck field
  $field_name_for_the_target = variable_get('glossify_use_this_cck_field_for_target_url_override', 'none');
  $field_name_for_the_target_name_of_the_value_column = $field_name_for_the_target . "_value";
  
  
  if ($field_name_for_the_target != 'none' ) {
   $target_vals_table_name = __glossify_get_val_table_from_cck_field_name($field_name_for_the_target);
  }

  // get terms from DB
  $result_3 = db_query("SELECT title, nid FROM {node} node WHERE $where_clause");
  while ($obj_3 = db_fetch_object($result_3)) {
    $nid = $obj_3->nid;

    
    if ( $field_name_for_the_target != 'none'  ) {
      $result_2 = db_query("
        SELECT vals_table.vid, vals_table.nid, vals_table.%s FROM {" . $target_vals_table_name . "} vals_table
        JOIN {node} node
          ON vals_table.vid = node.vid
        WHERE %s IS NOT NULL
          AND vals_table.nid = %d
      ", $field_name_for_the_target_name_of_the_value_column, $field_name_for_the_target_name_of_the_value_column, $nid);
    
      if ($obj_2 = db_fetch_object($result_2) ) {
        $target = $obj_2->{$field_name_for_the_target_name_of_the_value_column};
      }
      // empty - use node nid
      else {
        $target = 'node/' . $nid;
      }
    }
    else {
      $target = 'node/' . $nid;
    }
    
    
    $glossify_dict[$obj_3->title] = $target;
  }

  $synonyms_dict = glossify_get_synonyms();
  
  if (!empty($synonyms_dict)) {
    foreach ($synonyms_dict as $title => $target_url ) {
      $glossify_dict[$title] = $target_url;
    }
  }
  

  
  
  
  // sort the array by string length - long strings first
  if (!empty($glossify_dict) ) {
    uksort($glossify_dict, "__glossify_sort_array_by_keys_string_length_cmp");
    $glossify_dict_titles = array_keys($glossify_dict);
  }

  
  //print_r($glossify_dict);
  
}




function __glossify_get_val_table_from_cck_field_name($field_name) {
  // otidi vyv f ins i vzemi vsi4ki gloss inst
  // ako e samo 1 - tyrsi gloss vals v node_ctype
  // ako sa pove4e - vyv content_field_gloss
  $how_many_cck_instances_we_have =
    db_result(db_query("SELECT COUNT(*) FROM {content_node_field_instance} WHERE field_name = '%s' ",
    $field_name));
  
  $result = db_query("SELECT type_name FROM {content_node_field_instance} WHERE field_name = '%s' ",
    $field_name);
  while ( $obj = db_fetch_object($result) ) {
    $cck_types_that_have_this_field[] = $obj->type_name;
  }
    
    
  if (    $how_many_cck_instances_we_have == "0") {
    // some warning?
  }
  elseif ($how_many_cck_instances_we_have == "1") {
    // look into the type table
    $vals_table_name = "content_type_" . $cck_types_that_have_this_field[0];
  }
  // look into content_field_glossify_synonyms for example
  else {
    $vals_table_name = "content_" . $field_name;
  }

  return $vals_table_name;
  
}



function glossify_get_synonyms() {
  /////////
  // inject synonyms
  //$glossify_dict['turpis'] = "5";
  // get synonyms from nodes
  $field_name_for_the_synonyms = variable_get('glossify_use_this_cck_field_for_keyword_synonyms', 'none');
  
  if ( $field_name_for_the_synonyms == 'none' ) {return array(); }
  
  $field_name_for_the_synonyms_name_of_the_value_column = $field_name_for_the_synonyms . "_value";
  
  $syn_vals_table_name = __glossify_get_val_table_from_cck_field_name($field_name_for_the_synonyms);

  // for target cck field
  $field_name_for_the_target = variable_get('glossify_use_this_cck_field_for_target_url_override', '');
  $field_name_for_the_target_name_of_the_value_column = $field_name_for_the_target . "_value";
  
  if ( $field_name_for_the_target != 'none'  ) {
    $target_vals_table_name = __glossify_get_val_table_from_cck_field_name($field_name_for_the_target);
  }
  
  
  $result = db_query("
    SELECT vals_table.vid, vals_table.nid, vals_table.%s FROM {" . $syn_vals_table_name . "} vals_table
    JOIN {node} node
      ON vals_table.vid = node.vid
    WHERE %s IS NOT NULL
  ", $field_name_for_the_synonyms_name_of_the_value_column, $field_name_for_the_synonyms_name_of_the_value_column );
  
  while ( $obj = db_fetch_object($result) ) {
    $cck_vals = explode(",", $obj->{$field_name_for_the_synonyms_name_of_the_value_column} );
    $nid = $obj->nid;
    
    if (!empty($cck_vals) ) {
      
      if ( $field_name_for_the_target != 'none' ) {
      
        $result_2 = db_query("
          SELECT vals_table.vid, vals_table.nid, vals_table.%s FROM {" . $target_vals_table_name . "} vals_table
          JOIN {node} node
            ON vals_table.vid = node.vid
          WHERE %s IS NOT NULL
            AND vals_table.nid = %d
        ", $field_name_for_the_target_name_of_the_value_column, $field_name_for_the_target_name_of_the_value_column, $nid);
  
        if ($obj_2 = db_fetch_object($result_2) ) {
          $target = $obj_2->{$field_name_for_the_target_name_of_the_value_column};
        }
        // empty - use node nid
        else {
          $target = 'node/' . $nid;
        }
      
      }
      else {
        $target = 'node/' . $nid;
      }
      
      foreach ($cck_vals as $val) {
        $val_trimmed = trim($val, " ");
        // now we have the keywords
        // check for target overrides  and if any - use them
        $syn_dict[$val_trimmed] = $target;
      }
    }
  }
  //drupal_set_message("<pre>" . print_r($syn_dict, true));
  
  return $syn_dict;
}

/**
 * Implementation of hook_init().
 */
function glossify_init() {

  _glossify_build_dictionary_of_link_to_terms();

  global $glossify_style;
  $glossify_style = variable_get('glossify_style', 'links');

  // add css only on pages that will be parsed
// TODO add it only if at least one reason (page/teaser)
//  drupal_add_css(drupal_get_path('module', 'glossify') . '/glossify.css');
}


/**
 * Implementation of hook_nodeapi().
 * - alter: alter body/teaser after all input filters
 * - view: do sth on view
 *
 * @param unknown_type $node
 * @param unknown_type $op
 * @param unknown_type $a3
 * @param unknown_type $a4
 * @return unknown_type
 */
function glossify_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {

  $node_type   = $node->type;
  $content_types_to_search = variable_get('glossify_content_types_to_search', node_get_types());

  // return, if we're not viewing an appropriate node
  if (!in_array($node_type, $content_types_to_search) ) {
    return;
  }

  $node_nid    = $node->nid;
  $node_body   = $node->body;
  //$node_body   = $node->content['body']['#value'];
  
  $node_teaser = $node->teaser;
  //$node_teaser = $node->content['teaser']['#value'];
  

  switch ($op) {

    case 'alter':
      if (variable_get('glossify_display_parsing_time_for_performance_debugging', FALSE) ) {$time = __glossify_timer_start(); }

      // parse teaser
      if (variable_get('glossify_teaser', TRUE) && $a3 == 1 ) { // $a3 == 1 means it is a teaser we are parsing
        global $glossify_style;
        global $glossify_dict;
        global $glossify_dict_titles;
        $replacements = __glossify_build_replacements($glossify_style, $glossify_dict, $node_nid);

        $node->teaser = __glossify_parse_html_text_and_replace_terms_safely($node_teaser, $glossify_dict_titles, $replacements);

      }

      if ( $a4 == 1 ) {      // render the page's body
        global $glossify_style;
        global $glossify_dict;
        global $glossify_dict_titles;
        $replacements = __glossify_build_replacements($glossify_style, $glossify_dict, $node_nid);

        $node->body = __glossify_parse_html_text_and_replace_terms_safely($node_body, $glossify_dict_titles,  $replacements);
      }
      if (variable_get('glossify_display_parsing_time_for_performance_debugging', FALSE) ) {__glossify_timer_stop($time); }

    break; // done with $op = 'alter'

    case 'view': // used for reference section display

      global $glossify_style;

      switch ($glossify_style) {

        case 'links':
          break;
        
        case 'reference':

          global $glossify_dict;
  
          foreach ($glossify_dict as $term_title => $term_nid) {

            //TODO: this is slow but right! make it fast by saving the found terms from the replacing func
            //        if (__glossify_tell_whether_term_is_present_somewhere_in_the_html_plaintext($node_body, $term_title) ) {
            if (preg_match('/' . preg_quote($term_title, '/') . '/', $node_body)) {
              $term_definition_list .= theme('glossify_term', $term_nid, $glossify_style);
            } // endif found a term to glossify
          } // endforeach looping through terms
        
        case 'hovertip':
        default:

          global $glossify_dict;

          foreach ($glossify_dict as $term_title => $term_nid) {
      
            //TODO: this is slow but right! make it fast by saving the found terms from the replacing func
            //        if (__glossify_tell_whether_term_is_present_somewhere_in_the_html_plaintext($node_body, $term_title) ) {
            if (preg_match('/' . preg_quote($term_title, '/') . '/', $node_body)) {
              $node->content['glossify'][$term_title] = array(
                '#value' => theme('glossify_term', $term_nid, $glossify_style),
                '#weight' => 10,
              );
              $node->content['glossify']['#weight'] = 10;
            } // endif found a term to glossify
          } // endforeach looping through terms

          break;
            
      } // endswitch glossify style
    
    
      // make reference section under the node
      if ($glossify_style == 'reference') {
        $node->content['glossify'] = array(
          '#weight' => '10',
          '#value'  => theme('glossify_reference_section', $term_definition_list),
          );
      } // endif make reference section
    
      break; // break case view op
    
  } // endswitch $op
} // endfunction glossify_nodeapi



// works only for equal length arrays
function __glossify_str_replace_once($needles, $replacements, $haystack) {
  // Looks for the first occurence of $needle in $haystack
  // and replaces it with $replace.
  $i = -1;
  foreach ($needles as $needle_el) {
    $i++;
    $pos = strpos($haystack, $needle_el);
    // if nothing found, next loop
    if ($pos === FALSE) {
      continue;
    }
    // else
    $haystack = substr_replace($haystack, $replacements[$i], $pos, strlen($needle_el));
  }
  
  return $haystack;
}


function __glossify_convert_string_array_to_array_of_escaped_regexps($needles) {

  if (variable_get('glossify_do_we_need_unicode_compatibility', TRUE) ) {
    foreach ($needles as $needle) {
      // this below is Unicode compatible
      $regexps[] = "/(?<!\p{L})" . preg_quote($needle, "/") . "(?!\p{L})/u";
    }
  }
  // only latin
  else {
    foreach ($needles as $needle) {
     // this below is only-latin chars compatible
       $regexps[] = "/\b" . preg_quote($needle, "/") . "\b/";
    }
  }
  return $regexps;
}


function __glossify_replace($needles, $replacements, $haystack) {

  // take care of htmlentities so that the replacements can happen
  $haystack = html_entity_decode($haystack, ENT_COMPAT, "UTF-8");

  // use regexp? (forced by the don't break words option)
  if (variable_get('glossify_dont_break_words', TRUE) ) {

    // replace only one time?
    if (variable_get('glossify_link_first_only', TRUE) ) {
      $number_of_replacements = 1;
    }
    else {
      // all
      $number_of_replacements = -1;
    }

      $haystack = preg_replace( __glossify_convert_string_array_to_array_of_escaped_regexps($needles), $replacements, $haystack, $number_of_replacements);
  
  }
  else { // uses str_replace for performance

    // replace only one time
    if (variable_get('glossify_link_first_only', TRUE) ) {
      // replace only 1st occurence
      // this is a str_replace with array args
      $haystack = __glossify_str_replace_once($needles, $replacements, $haystack);
    }
    else {
      // replace all occurencies
      // str replace with array args
      $haystack = str_replace($needles, $replacements, $haystack);
    }
  
  }
  

// escape again the htmlentities - useful for non autolinked characters - so they are returned to their previous html-entities-state
// (autolinked chars are whatever the link-to titles/strings are ...)
  $haystack = htmlentities($haystack, ENT_COMPAT, "UTF-8");

  return $haystack;
}



function __glossify_parse_html_text_and_replace_terms_safely($input_html, $glossary_terms_search_for, $replacements) {

  // Create a simplehtmldom object
  $html_obj = new simple_html_dom();
  // Load HTML from a string
  $html_obj->load($input_html);

  
  // escape a tags - phase 1
  $i=-1;
  foreach ($html_obj->find('a') as $obj) {
    $i++;
    $a_marker = "<!--[_a_" . $i . "_a_]-->"; // so they are now html-tags and get packed into them
    $a_markers[$i]   = $a_marker;
    // save the real tags' text now - so you can unescape them later
    $a_unescaped[$i] = $obj->outertext;
    // the actual escaping happens
    $obj->outertext          = $a_marker;
  }
  

  
  // implode-explode all-in-one-go parsing
  // 1. stick together
  $glue = "[_p__p_]";
  $plain_text_string = implode($glue, $html_obj->find('text'));

  // escape replacements - so that link-to-places that are substring of other ltp-s do not cause...
  // the a-tag into a-tag situation
  
   // escape replacements
  $i=-1;
  foreach ($replacements as $replacement) {
    $i++;
    $repl_marker = "[_r_" . $i . "_r_]";
    $repl_markers[$i]   = $repl_marker;
    // save the real strings now - so you can unescape them later
    $repl_unescaped[$i] = $replacement;
    // the actual escaping happens just below
  }
  
  // do string or preg replace - only 1st OR all occurencies - all depends on the settings of the module
  $plain_text_string = __glossify_replace($glossary_terms_search_for, $repl_markers, $plain_text_string);
  
  //unescape replacements
  $plain_text_string = str_replace($repl_markers, $repl_unescaped, $plain_text_string);
  
  $plain_text_objects_array = explode($glue, $plain_text_string);
  
  $i = -1;
  foreach ($html_obj->find('text') as $plain_text_obj ) {
    $i++;
    $plain_text_obj->outertext = $plain_text_objects_array[$i] ;
  
  } // end foreach plaintext chunk

  
  // convert obj to string
  $html_obj_string = $html_obj->save();

  // clear memory
  $html_obj->clear();

  // unescape a tags - phase 2 - ending phase -
  // then return the parsed_html
  return str_replace($a_markers, $a_unescaped, $html_obj_string);
}



function __glossify_tell_whether_term_is_present_somewhere_in_the_html_plaintext($input_html, $term_title) {

  // Create a DOM object
  $html_obj = new simple_html_dom();
  // Load HTML from a string
  $html_obj->load($input_html);

  // look only in plaintext html parts - ommit inside html tags - like in <a here> </here>
  foreach ($html_obj->find('text') as $plain_text_obj ) {
      if (strstr($plain_text_obj->outertext, $term_title) !== FALSE ) {
        $html_obj->clear();
        return TRUE;
      }
  } // end foreach plaintext chunk
  
  return FALSE;
}


function __glossify_sort_array_by_keys_string_length_cmp($str1, $str2) {
  $strlen_1 = strlen($str1);
  $strlen_2 = strlen($str2);
  
  if ($strlen_1 == $strlen_2 ) {
    return 0;
  }
  return ($strlen_1 > $strlen_2) ? -1 : 1;
}


function __glossify_build_replacements($glossify_style, $glossary_terms, $node_nid) {
  // build replacement - needs term node title and term node id, returns replacement

  $node       = node_load($node_nid);
  $node_title = $node->title;

  foreach ($glossary_terms as $term_title => $target_url) {
  
    // TODO self-linking improve it for synonyms too
    // don't link to myself - just replace the term with itself (without a link - just string)
    if ( $term_title == $node_title ) {
      $replacements[] = $term_title; continue;
    } // next loop

    switch ($glossify_style) {
      
      case 'links':
        // TODO a title custom
        $replacements[] = l($term_title, $target_url,
          array('attributes' => array('title' => $term_title, 'class' => 'glossify_term')));
      break;
    
      case 'reference':
        $replacements[] = '<span class="glossify_term">' . $term_title . '</span>';
      break;

      case 'hovertip':

      default:
        $replacements[] = '<span class="glossify_term hovertip_target" hovertip="' . $term_title . '">' . $term_title . '</span>';
      break;
    } // endswitch glossify style
  }// end foreach term
  
  return $replacements;

} // end func __glossify_build_replacements


function __glossify_timer_start() {
  $mtime = explode(' ', microtime() );
  return $mtime[1] + $mtime[0];
}


function __glossify_timer_stop($starttime) {
  $mtime = explode(' ', microtime() );
  $endtime = $mtime[1] + $mtime[0];
  echo '<br>This page was parsed by Glossify in ' . ($endtime - $starttime) . ' seconds.';
}


/**
 * Form builder for administrative settings.
 */
function glossify_admin_settings() {
  
  if (!module_exists("content")) {
    $form['glossify_enable_cck_please'] = array(
      '#type' => 'checkbox',
      '#title' => t('(Dummy checkbox) Please download and enable the module "content" which is the core <a href="http://drupal.org/project/cck">CCK</a> module.'),
      '#default_value' => "",
    );
    
  }
  else {
    
    $form['glossify_content_types_to_search'] = array(
      '#type' => 'select',
      '#title' => t('"Link-FROM" content types - We look for keywords into their text and replace them with links'),
      '#multiple' => TRUE,
      '#options' => node_get_types('names'),
      '#default_value' => variable_get('glossify_content_types_to_search', ''),
    );
    
    $form['glossify_glossary_content_type'] = array(
      '#type' => 'select',
      '#title' => t('"Link-TO" content types. (node-title = keyword)'),
      '#multiple' => TRUE,
      '#options' => node_get_types('names'),
      '#default_value' => variable_get('glossify_glossary_content_type', ''),
      );
      
    $form['glossify_link_first_only'] = array(
      '#type' => 'checkbox',
      '#title' => t('Only link first occurance of term. On by default. If unchecked all occurences are replaced.'),
      '#default_value' => variable_get('glossify_link_first_only', TRUE),
    );
  
    $form['glossify_do_we_need_unicode_compatibility'] = array(
      '#type' => 'checkbox',
      '#title' => t('Do we need Unicode compatibility?. Check this if you need Unicode support. If not checked, non-latin words would not get autolinked.<br>
                     If you get php warnings with this setting=On - then please update/fix your PCRE PHP-library.'),
      '#default_value' => variable_get('glossify_do_we_need_unicode_compatibility', TRUE),
    );
  
    $form['glossify_teaser'] = array(
      '#type' => 'checkbox',
      '#title' => t('Link content in teaser'),
      '#default_value' => variable_get('glossify_teaser', TRUE),
    );
    $form['glossify_style'] = array(
      '#type' => 'select',
      '#title' => t('Style of glossary terms.'),
      '#options' => array(
        'hovertip' => t('Hovertips'),
        'links'     => t('Links'),
        'reference' => t('Reference section under content'),
      ),
      '#default_value' => variable_get('glossify_style', 'hovertip'),
      '#description' => t('How the glossary should be styled. Note: "hovertip" style requires hovertip.module. If you choose anything other than links - it should work but for now it is untested territory - feedback welcome.'),
    );
  
    
    $form['glossify_dont_break_words'] = array(
      '#type' => 'checkbox',
      '#title' => t('Check this to NOT break words. This means that the keyword "bla" will not linkify the bla-part of "blade". We use this regexp to make this work: "/\b$keyword_term\b/".'),
      '#default_value' => variable_get('glossify_dont_break_words', TRUE),
    );
  
  
    $form['glossify_display_parsing_time_for_performance_debugging'] = array(
      '#type' => 'checkbox',
      '#title' => t('Show a small debug timer at top of glossify-parsed pages. Off by default.'),
      '#default_value' => variable_get('glossify_display_parsing_time_for_performance_debugging', FALSE),
    );
  
    //
    
    foreach (array_keys(content_fields()) as $key ) {
      $all_cck_field_names[$key] = $key;
    }
    $all_cck_field_names['none'] = 'none';
    
    $form['glossify_use_this_cck_field_for_keyword_synonyms'] = array(
      '#type' => 'select',
      '#title' => t("CCK field to look into for synonyms of the node's title. For more than 1 content type - use the same cck field please."),
      '#options' => $all_cck_field_names,
      '#default_value' => variable_get('glossify_use_this_cck_field_for_keyword_synonyms', 'none'),
      '#description' => t('Select a CCK field for synonyms.'),
    );
  
    $form['glossify_use_this_cck_field_for_target_url_override'] = array(
      '#type' => 'select',
      '#title' => t("CCK field to look into for a 'target url override'. For more than 1 content type - use the same cck field please."),
      '#options' => $all_cck_field_names,
      '#default_value' => variable_get('glossify_use_this_cck_field_for_target_url_override', 'none'),
      '#description' => t("Select a CCK field for target override.  After you create the cck field and then put something into it
        Example: 'node/34', 'url_alias', 'http://example.com/path' this will make the target url point to your override path."),
    );
    
  }
  // system_settings_form: Add default buttons to a form and set its prefix.
  // then return it to the page callback of the menu (drupal_get_form)
  return system_settings_form($form);
}



/**
 * Implementation of hook_perm().
 */
function glossify_perm() {
  return array('administer glossify');
}



/**
 * Render a glossary term.
 */
function theme_glossify_term($nid, $glossify_style) { // outputs proper div so hovertip will work
  $term = node_load($nid);
  switch ($glossify_style) {
    case 'reference':
      $output = '<dt>' . $term->title . '</dt>';
      $output .= '<dd>' . $term ->body . '</dd>';
      break;
    case 'hovertip':
    default:
      $output = '<div id="' . $term->title . '" class="hovertip" style="display: none;">';
      // Output a DIV to make hovertip work.
      $output .= '<h1>' . $term->title . '</h1>';
      $output .= '<p>' . $term->body . '</p>';
      $output .= '</div>';
      break;
  } // endswitch glossify style
  return $output;
}


/**
 * Implementation of hook_theme().
 */
function glossify_theme() {
  return array(
    'glossify_term' => array(
      'arguments' => array('nid' => NULL, 'glossify_style' => NULL),
    ),
    'glossify_reference_section' => array(
      'arguments' => array('term_definition_list' => NULL),
    ),
  );
} // endfunction glossify_theme


/**
 * Render a glossary term reference.
 */
function theme_glossify_reference_section($term_definition_list) {
  $output = '<div id="glossify-reference">';
  $output .= '<h3>Terms referenced:</h3>';
  $output .= '<dl>';
  $output .= $term_definition_list;
  $output .= '</dl>';
  $output .= '</div>';
  return $output;
}

