<?php
// $Id: views_modify_query.module,v 1.2 2008/09/15 16:28:56 anselmheaton Exp $

/**
 * Implementation of hook_help().
 */
function views_modify_query_help($section, $arg) {
  switch ($section) {
    case 'admin/modules#description':
      return t('A views filter that lets users enter PHP code to modify the query object directly. Advanced developers only.');
  }
}


/**
 * Implementation of hook_views_api
 */
function views_modify_query_views_api() {
  return array(
    'api' => '2.0',
    'path' => drupal_get_path('module', 'views_modify_query'),
  );
}


