<?php
// $Id:

/**
 * @file
 * Maintains galleries of nodes in arbitrary order.
 */

/* --- HOOKS ---------------------------------------------------------------- */

/**
 * Implementation of hook_access
 */
function photo_gallery_access($op, $node, $account) {
	if ($op == 'create') {
    	// Only users with permission to do so may create this node type.
    	return user_access('create photo_gallery', $account);
  	}

  // Users who create a node may edit or delete it later, assuming they have the
  // necessary permissions.
  if ($op == 'update' || $op == 'delete') {
    if (user_access('edit photo_gallery', $account) && ($account->uid == $node->uid)) {
      return TRUE;
    }
  }
}

/**
 * Implementation of hook_info
 */
function photo_gallery_node_info() {
	return array(
    'photo_gallery' => array(
      'name' => t('Photo Gallery'),
      'module' => 'photo_gallery',
      'description' => "Create a collection of nodes which can be arranged in an arbitrary order.",
      'has_title' => TRUE,
      'title_label' => t('Gallery Title'),
      'has_body' => TRUE,
      'body_label' => t('Gallery Body'),
    )
  );
}

/**
 * Implementation of hook_form
 */
function photo_gallery_form(&$node) {
 // The site admin can decide if this node type has a title and body, and how
  // the fields should be labeled. We need to load these settings so we can
  // build the node form correctly.
  $type = node_get_types('type', $node);

  if ($type->has_title) {
    $form['title'] = array(
      '#type' => 'textfield',
      '#title' => check_plain($type->title_label),
      '#required' => TRUE,
      '#default_value' => $node->title,
      '#weight' => -5,
    );
  }

  if ($type->has_body) {
    // In Drupal 6, we can use node_body_field() to get the body and filter
    // elements. This replaces the old textarea + filter_form() method of
    // setting this up. It will also ensure the teaser splitter gets set up
    // properly.
    $form['body_field'] = node_body_field($node, $type->body_label, $type->min_word_count);
  }
  
  // set a count of how many nodes you can add.
  $form['size'] = array(
    '#type' => 'textfield',
    '#title' => t('Size'),
    '#default_value' => isset($node->size) ? $node->size : '0',
    '#size' => 2,
    '#maxlength' => 2,
    '#description' => t('The maximum number of nodes will appear in the gallery. Enter 0 for no limit'),

  );
  
  $nodes = node_get_types('names');

  $form['types'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Types'),
    '#default_value' => is_array($node->types) ? $node->types : array(),
    '#options' => $nodes,
    '#description' => t('Check each node type that can be added to this gallery.'),
  ); 
 
  return $form;
}

/**
 * Implementation of hook_perm
 */
function photo_gallery_perm() {
  return array('edit photo_gallery', 'create photo_gallery');
}

/**
 * Implementation of hook_help
 */
function photo_gallery_help() {
	//TODO add some help info
	switch ($path) {
    	case 'admin/help#photo_gallery':
      		return '<p>'. t('Create a collection of nodes which can be arranged in an arbitrary order.') .'</p>';
  }
}

/**
 * Implementation of hook_validate().
 *
 * Our "quantity" field requires a number to be entered. This hook lets
 * us ensure that the user entered an appropriate value before we try
 * inserting anything into the database.
 *
 * Errors should be signaled with form_set_error().
 */
function photo_gallery_validate(&$node) {
 if ($node->quantity) {
    if (!is_numeric($node->quantity)) {
      form_set_error('quantity', t('The quantity must be a number.'));
    }
  }
  else {
    // Let an empty field mean "zero."
    $node->quantity = 0;
  }
}

/**
 * Implementation of hook_insert().
 *
 * As a new node is being inserted into the database, we need to do our own
 * database inserts.
 */
function photo_gallery_insert($node) {
  db_query("INSERT INTO {photo_gallery} (nid, vid, size) VALUES (%d, %d, %d)", $node->nid, $node->vid, $node->size);
  // TODO insert content types
  if (is_array($node->types)) {
    foreach ($node->types as $type) {
    	if (!empty($type)) {
      		db_query("INSERT INTO {photo_gallery_types} (nid, vid, type) VALUES (%d, %d, '%s')", $node->nid, $node->vid, $type);
      	}
  	}
  }
  //return $queue->qid;
}

/**
 * Implementation of hook_update().
 *
 * As an existing node is being updated in the database, we need to do our own
 * database updates.
 */
function photo_gallery_update($node) {
  // if this is a new node or we're adding a new revision,
  if ($node->revision) {
    photo_gallery_insert($node);
  }
  else {
    db_query("UPDATE {photo_gallery} SET size = %d WHERE vid = %d", $node->size, $node->vid);
    db_query("DELETE FROM {photo_gallery_types} WHERE vid = %d", $node->vid);
    if (is_array($node->types)) {
    	foreach ($node->types as $type) {
    		if (!empty($type)) {
      			db_query("INSERT INTO {photo_gallery_types} (nid, vid, type) VALUES (%d, %d, '%s')", $node->nid, $node->vid, $type);
      		}
  		}
  	}
  	//TODO add update to image node associations
  }
}

/**
 * Implementation of hook_nodeapi().
 *
 * When a node revision is deleted, we need to remove the corresponding record
 * from our table. The only way to handle revision deletion is by implementing
 * hook_nodeapi().
 */
function photo_gallery_nodeapi(&$node, $op, $teaser, $page) {

  switch ($op) {
    case 'delete revision':
      // Notice that we're matching a single revision based on the node's vid.
      db_query('DELETE FROM {photo_gallery_types} WHERE vid = %d', $node->vid);
      db_query('DELETE FROM {photo_gallery_nodes} WHERE vid = %d', $node->vid);
      db_query('DELETE FROM {photo_gallery} WHERE vid = %d', $node->vid);
      break;
  }
}

/**
 * Implementation of hook_delete().
 *
 * When a node is deleted, we need to remove all related records from out table.
 */
function photo_gallery_delete($node) {
  // remove associated data first, then the gallery.
  db_query('DELETE FROM {photo_gallery_nodes} WHERE nid = %d', $node->nid);
  db_query('DELETE FROM {photo_gallery_types} WHERE nid = %d', $node->nid);
  db_query('DELETE FROM {photo_gallery} WHERE nid = %d', $node->nid);
}

/**
 * Implementation of hook_load().
 *
 * Now that we've defined how to manage the node data in the database, we
 * need to tell Drupal how to get the node back out. This hook is called
 * every time a node is loaded, and allows us to do some loading of our own.
 */
function photo_gallery_load($node) {
 	$additions = db_fetch_object(db_query('SELECT size FROM {photo_gallery} WHERE vid = %d', $node->vid));
 	$types = db_query('SELECT type from {photo_gallery_types} WHERE vid = %d', $node->vid);
 	$additions->types = array();
 	while ($type = db_fetch_object($types)) {
 		$additions->types[] = $type->type;
 	}
 	$additions->nodes = photo_gallery_load_nodes($node->vid, 0, 0);
    return $additions;
}

function photo_gallery_load_nodes($vid, $from = 0, $count = null, $published_only = TRUE) {
 	$orderby = "ASC";
  	if ($published_only) {
    	$published_sql = 'AND n.status = 1';
  	}
  	
  	$sql = db_rewrite_sql("SELECT n.nid, nn.override_title, nn.override_link, nn.imagecache_setting FROM {node} n INNER JOIN {photo_gallery_nodes} nn ON n.nid = nn.cnid WHERE nn.vid = %d $published_sql ORDER BY nn.position $orderby");
  	
  	if ($count) {
    	$result = db_query_range($sql, $vid, $from, $count);
  	}
  	else {
    	$result = db_query($sql, $vid);
  	}

  	$nodes = array();
  	if ($result) {
  		while ($galleryNode = db_fetch_object($result)) {
  			$node = node_load($galleryNode->nid);
  			$nodes[]= (object) array_merge((array) $galleryNode, (array) $node);
    		//$nodes[] = node_load($galleryNode->nid);
  		}
  	}

  	return $nodes;
}

/**
 * Implementation of hook_init().
 *
 * Loads subsidiary includes for other modules.
 */
function photo_gallery_init() {
 // drupal_flush_all_caches();
	//menu_rebuild();
  include_once drupal_get_path('module', 'photo_gallery') .'/include/photo_gallery_theme.inc';
}

function _photo_gallery_manage_items(&$photo_gallery) {
// var_dump($photo_gallery);
 	if (!isset($photo_gallery->nodes)) {
 		$photo_gallery->nodes = photo_gallery_load_nodes($photo_gallery->vid, 0, 0);
 	}
	
	$content = theme('photo_gallery_items_admin', $photo_gallery->nodes, $photo_gallery->nid, $photo_gallery->vid);
	return $content;
 }
 
 function _photo_gallery_manage_access($node=false) {
 	if (($node && $node->type == 'photo_gallery')) return true;
 	else return false;
 }

/**
 * Implementation of hook_menu
 */
function photo_gallery_menu() {

  $items = array();
	// administrative items

  $items['node/%node/manage'] = array(
		'title' 		=> 'Manage Images',
		'access callback' => '_photo_gallery_manage_access',
		'page callback' => '_photo_gallery_manage_items',
    	'page arguments' => array(1),
    	'access arguments' => array(1),
		'description' 	=> 'Manage which content nodes to include in gallery',
		'type'			=> MENU_LOCAL_TASK
  );
  
  $items['admin/photo_gallery/browse_items'] = array(
		'title' 		=> 'browse items',
		'access callback' => TRUE,
		'page callback' => 'photo_gallery_imagebrowser',
    	//'page arguments' => array(1),
    	//'access arguments' => array(true),
		'description' 	=> 'Browse image nodes',
		'type'			=> MENU_CALLBACK
  );
  
  $items['admin/photo_gallery/add_items'] = array(
		'title' 		=> 'browse items',
		'access callback' => TRUE,
		'page callback' => 'photo_gallery_add_nodes',
    	//'page arguments' => array(1),
    	//'access arguments' => array(true),
		'description' 	=> 'Browse image nodes',
		'type'			=> MENU_CALLBACK
  );
  
  $items['admin/photo_gallery/update_item'] = array(
		'title' 		=> 'update item data',
		'access callback' => TRUE,
		'page callback' => '_photo_gallery_update_item',
    	//'page arguments' => array(1),
    	//'access arguments' => array(true),
		'description' 	=> 'Updates item settings',
		'type'			=> MENU_CALLBACK
  );
    
  $items['admin/photo_gallery/item_data'] = array(
		'title' 		=> 'get item dat',
		'access callback' => TRUE,
		'page callback' => '_photo_gallery_item_data',
    	//'page arguments' => array(1),
    	//'access arguments' => array(true),
		'description' 	=> 'get item settings',
		'type'			=> MENU_CALLBACK
  );
  return $items;
}
/**
 * update settings for a node attached to the gallery
 */
 function _photo_gallery_update_item() {
 //	$galleryId = $_POST['gid'];
 	$gvid = $_POST['gvid'];
 	$nodeId = $_POST['nid'];
 	
 	 db_query("UPDATE {photo_gallery_nodes} SET override_title = '%s', override_link = '%s', imagecache_setting = '%s' WHERE vid = %d and cnid= %d", $_POST['override_title'], $_POST['override_link'], $_POST['imagecache_settings'], $gvid, $nodeId);
 }
 
 function _photo_gallery_item_data() {
 	$cnid = $_POST['cnid'];
 	$vid = $_POST['vid'];
 	$data  = db_fetch_object(db_query('SELECT * FROM {photo_gallery_nodes} WHERE vid = %d and cnid= %d', $vid, $cnid));
 	 drupal_get_messages(null, true);
 	echo drupal_to_js($data);
 }
 
/**
 * The image browser powered by Views.
 */
function photo_gallery_imagebrowser() {
	//$output = "";
	$searchTerm = (!empty($_POST)) ? $_POST['search_term'] : false;
	$nodes = array();
	if (false && !$searchTerm) { // this will only happen when there are no search terms
		$types = array('img');//TODO get this from the photo gallery settings
		$type_str = "'" . implode("', '", $types) . "'";
		$sql = "SELECT node.nid AS nid FROM node WHERE node.type in ($type_str)";
		$results = db_query($sql);
		while ( $data = db_fetch_object($results) ) {
  			$nodes[] = node_load($data->nid);
  			//$output .= node_view($node);
		}
	} else { // we must have some search terms
		//$searchTerms = 'hip-hop';
		//echo $searchTerm;
		$find = do_search($searchTerm, 'node', 'INNER JOIN {node} n ON n.nid = i.sid', '(n.type = "img")');
         // Load results.
      	$results = array();
      	foreach ($find as $item) {
        	// Build the node body.
        	$nodes[] = node_load($item->sid);
        }
    }
    
   echo  photo_gallery_items_browse($nodes);
}

function photo_gallery_add_nodes() {
	$galleryVid = $_POST['vid'];
	$galleryNid = $_POST['nid'];
	$galleryNodeIds = explode(",", $_POST['nodeIds']);
	db_query('DELETE FROM {photo_gallery_nodes} WHERE vid = %d', $galleryVid);
	if (!empty($galleryVid) && !empty($galleryNodeIds)) {
		print 'sees nodes!';
		$i = 1;
		foreach ($galleryNodeIds as $cnid) {
    		if (!empty($cnid)) {
    			//print "INSERT INTO {photo_gallery_nodes} (nid, vid, cnid, position, timestamp) VALUES ($galleryNid, $galleryVid, $cnid, 1, " . time() . ")\n";
      			db_query("INSERT INTO {photo_gallery_nodes} (nid, vid, cnid, position, timestamp) VALUES (%d, %d, %d, %d, %d )", $galleryNid, $galleryVid, $cnid, $i, time());
      		}
			$i++;
  		}

		
	}

	node_init();
        global $memcache;
        $memcache->delete($memcache->drupal_prefix . $galleryNid);
}

/**
 *
 * Now that we've defined how to manage the node data in the database, we
 * need to tell Drupal how to get the node back out. This hook is called
 * every time a node is loaded, and allows us to do some loading of our own.
 */
function photo_gallery_load_by_term($term, $reset=true) {
	static $module_data;
	$termId = 18; //todo get this based on term
	$cache_key = 'photo_gallery-' . $term;
	if (!isset($module_data) || $reset) {
    	if (!$reset && ($cache = cache_get($cache_key)) && !empty($cache->data)) {
      		$module_data = unserialize($cache->data);
    	} else {
			// Do your expensive calculations here, and populate $my_data
      		// with the correct stuff..
      		$sql = "SELECT node.nid AS nid, node.vid as vid, node.changed AS node_changed FROM node node INNER JOIN term_node term_node ON node.vid = term_node.vid WHERE (node.status <> 0) AND (term_node.tid = $termId) AND (node.type in ('photo_gallery')) ORDER BY node_changed DESC";
      		$result =  db_fetch_object(db_query($sql));
      		$module_data = photo_gallery_load($result);
      		cache_set($cache_key, serialize($module_data), 'cache', time() + 360);
    }
  }
  return $module_data;
}
