<?php
// $Id$

/**
 * @file
 * TODO: Enter file description here.
 */

/**
 * Implementation of hook_menu().
 */
 
function jp_vlinks_block($op='list', $delta=0, $edit=array()) {
 switch ($op) {
 case 'list':
 $blocks[0]['info'] = t('V-Links Module Block');
 return $blocks;
 case 'view':
 $vibe = get_jp_vlinks();
 $vibe_variables = array('vlinks' => $vibe);
 $blocks['content'] = theme_render_template('sites/all/themes/vibe/jp_vlinks.tpl.php',$vibe_variables);
 return $blocks;
 }
} 
 
 
function jp_vlinks_menu() { 
	$items['admin/content/jp_vlinks'] = array(
    'title' => 'Vlinks',
    'description' => 'Manage vlinks configurations.',
    'page callback' => 'jp_vlinks_admin',
    'access arguments' => array('administer jp_vlinks'),
  );
  
  $items['admin/content/jp_vlinks/list'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  
   $items['admin/content/jp_vlinks/edit'] = array(
    'title' => 'Edit Vlink',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('jp_vlinks_form_config'),
    'access arguments' => array('administer jp_vlinks'),
    'type' => MENU_LOCAL_TASK,
    'parent' => 'admin/content/jp_vlinks',
    //'file' => 'taxonomy.admin.inc',
  );
  
  return $items;

}

function jp_vlinks_perm() {
  return array('administer jp_vlinks', 'edit jp_vlinks');
}

function jp_vlinks_admin(){
	$jp_vlinks = get_jp_vlinks();
	//var_dump($jp_vlinks->main_link);
		$rows = array();
	
		$row = array();
		$row[] = theme('imagecache', 'vlinks-cropping', $jp_vlinks->vlink_image_path, '', '');
		$row[] = $jp_vlinks->main_link;
		$row[] = l(t('Edit V-Link'), "admin/content/jp_vlinks/edit/");
		$rows[] = array('data' => $row, 'class' => 'draggable');
	
	
	if (empty($rows)) {
    	$rows[] = array(array('data' => t('No Vlinks available.'), 'colspan' => '3'));
  	}
	
	$header = array(t('Image Path'));
	$header[] = array('data' => t('Main Link'));	
	$header[] = array('data' => t('Operations'));	
	return theme('table', $header, $rows, array('id' => 'jp_vlinks'));
}

function get_jp_vlinks(){

	
	$sql = "SELECT * FROM jp_vlinks_links INNER JOIN jp_vlinks_image AS image ON image.vlink_id = 1";
	$query = db_query($sql);
	$results = db_fetch_object($query);
	return $results;
}

function jp_vlinks_form_config(&$form_state){
	$links = get_jp_vlinks();
	
	$form['#attributes'] = array('enctype' => "multipart/form-data");
		
	$form['vlink_image_upload'] = array(
      '#type' => 'file',
      '#title' => t('Upload Vlink image'),
      '#size' => 60,
   );
   
   $form['main_link'] = array(
	'#type' => 'textfield',
    '#title' => t('Main Link Title'),
    '#default_value' => $links->main_link,
    '#description' => t('Main Link Title.'),
	'#required' => TRUE,
  );
  
  $form['main_link_url'] = array(
	'#type' => 'textfield',
    '#title' => t('Main Link URL'),
    '#default_value' => $links->main_link_url,
    '#description' => t('Main Link URL.'),
	'#required' => TRUE,
  );
  
  $form['main_link_source'] = array(
	'#type' => 'textfield',
    '#title' => t('Main Link Source'),
    '#default_value' => $links->main_link_source,
    '#description' => t('Main Link Source.'),
	'#required' => TRUE,
  );
  
  $form['link_1'] = array(
	'#type' => 'textfield',
    '#title' => t('Link 1 Title'),
    '#default_value' => $links->link_1,
    '#description' => t('Link 1 Title.'),
	'#required' => TRUE,
  );
  
  $form['link_1_url'] = array(
	'#type' => 'textfield',
    '#title' => t('Link 1 URL'),
    '#default_value' => $links->link_1_url,
    '#description' => t('Link 1 URL.'),
	'#required' => TRUE,
  );
  
  $form['link_1_source'] = array(
	'#type' => 'textfield',
    '#title' => t('Link 1 Source'),
    '#default_value' => $links->link_1_source,
    '#description' => t('Link 1 Source.'),
	'#required' => TRUE,
  );
  
  $form['link_2'] = array(
	'#type' => 'textfield',
    '#title' => t('Link 2 Title'),
    '#default_value' => $links->link_2,
    '#description' => t('Link 2 Title.'),
	'#required' => TRUE,
  );
  
  $form['link_2_url'] = array(
	'#type' => 'textfield',
    '#title' => t('Link 2 URL'),
    '#default_value' => $links->link_2_url,
    '#description' => t('Link 2 URL.'),
	'#required' => TRUE,
  );
  
  $form['link_2_source'] = array(
	'#type' => 'textfield',
    '#title' => t('Link 2 Source'),
    '#default_value' => $links->link_2_source,
    '#description' => t('Link 2 Source.'),
	'#required' => TRUE,
  );
  
  $form['link_3'] = array(
	'#type' => 'textfield',
    '#title' => t('Link 3 Title'),
    '#default_value' => $links->link_3,
    '#description' => t('Link 3 Title.'),
	'#required' => TRUE,
  );
  
  $form['link_3_url'] = array(
	'#type' => 'textfield',
    '#title' => t('Link 3 URL'),
    '#default_value' => $links->link_3_url,
    '#description' => t('Link 3 URL.'),
	'#required' => TRUE,
  );
  
  $form['link_3_source'] = array(
	'#type' => 'textfield',
    '#title' => t('Link 3 Source'),
    '#default_value' => $links->link_3_source,
    '#description' => t('Link 3 Source.'),
	'#required' => TRUE,
  );
  
  $form['link_4'] = array(
	'#type' => 'textfield',
    '#title' => t('Link 4 Title'),
    '#default_value' => $links->link_4,
    '#description' => t('Link 4 Title.'),
	'#required' => TRUE,
  );
  
  $form['link_4_url'] = array(
	'#type' => 'textfield',
    '#title' => t('Link 4 URL'),
    '#default_value' => $links->link_4_url,
    '#description' => t('Link 4 URL.'),
	'#required' => TRUE,
  );
  
  $form['link_4_source'] = array(
	'#type' => 'textfield',
    '#title' => t('Link 4 Source'),
    '#default_value' => $links->link_4_source,
    '#description' => t('Link 4 Source.'),
	'#required' => TRUE,
  );
  
  
  
  $form['submit'] = array('#type' => 'submit', '#value' => t('Save'));
  
  return $form;

}

function jp_vlinks_form_validate($form, &$form_state) {
  
  if($form_state['values']['main_link'] == "" || empty($form_state['values']['main_link']) || $form_state['values']['main_link'] == NULL ) {
    form_set_error('main_link', t('Main Link can not be empty.'));
  }
}

function jp_vlinks_form_config_submit($form, &$form_state) {

	
	$file = save_vlinks_image();
	if($file){		
		$sql_image = "UPDATE jp_vlinks_image SET vlink_id = '1',vlink_image_path = '%s'";
		db_query($sql_image,$file);
	}
	
	$main_link = $form_state['values']['main_link'];
	$main_link_url = $form_state['values']['main_link_url'];
	$main_link_source = $form_state['values']['main_link_source'];
	$link_1 = $form_state['values']['link_1'];
	$link_1_url = $form_state['values']['link_1_url'];
	$link_1_source = $form_state['values']['link_1_source'];
	$link_2 = $form_state['values']['link_2'];
	$link_2_url = $form_state['values']['link_2_url'];
	$link_2_source = $form_state['values']['link_2_source'];
	$link_3 = $form_state['values']['link_3'];
	$link_3_url = $form_state['values']['link_3_url'];
	$link_3_source = $form_state['values']['link_3_source'];
	$link_4 = $form_state['values']['link_4'];
	$link_4_url = $form_state['values']['link_4_url'];
	$link_4_source = $form_state['values']['link_4_source'];
	
	
	
	
	$sql_links = "UPDATE jp_vlinks_links SET vlink_id='1',main_link = '%s',main_link_url = '%s',main_link_source='%s',link_1='%s',link_1_url='%s',link_1_source='%s',link_2='%s',link_2_url='%s',link_2_source='%s',link_3='%s',link_3_url='%s',link_3_source='%s',link_4='%s',link_4_url='%s',link_4_source='%s'";
																																																																																																																																																																																																																																																													db_query($sql_links,$main_link,$main_link_url,$main_link_source,$link_1,$link_1_url,$link_1_source,$link_2,$link_2_url,$link_2_source,$link_3,$link_3_url,$link_3_source,$link_4,$link_4_url,$link_4_source);			
																																																																																																																																																																																																																																																												
	$form_state['redirect'] = 'admin/content/jp_vlinks';

}

function save_vlinks_image(&$form,&$form_state){
	$validators = array();	
	$directory = file_directory_path() . "/vlinks";
  	if (!file_check_directory($directory, FILE_CREATE_DIRECTORY)) {
     	drupal_set_message(t('Error creating the vlinks image directory: "%dir" does not exist, or is not writable.', array('%dir' => $directory)), 'error');
  	} else {
	  // FILE_EXISTS_REPLACE allows multiple terms to use the same image without having multiple files.      
	  	$file = file_save_upload('vlink_image_upload', $validators, $directory, FILE_EXISTS_REPLACE);
		if (is_object($file)) {
			// If no errors while uploading, save term-image relation into DB
			$filepath = $directory .'/'. $file->filename;
			$edit['vlinks_image_path'] =  $filepath;
			// TODO see if we need this, i dont think we do cache_clear_all("taxonomy_image:$tid", 'cache_tax_image');
			// make sure Cron doesn't delete this file.
			file_set_status($file, FILE_STATUS_PERMANENT);
			drupal_set_message(t('Image uploaded as @name.', array('@name' => $filepath)));
	  	}
  	}	
	return $filepath;
}
